/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsVerifyConnection } from "../../funcs/agentsVerifyConnection.js";
import { VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostRequest$zodSchema } from "../../models/verifyagentconnectionagentsagentuuidverifyconnectionpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostRequest$zodSchema,
};

export const tool$agentsVerifyConnection: ToolDefinition<typeof args> = {
  name: "verify-agent-connection",
  description:
    `Verify that a connection-type agent responds. Optionally pass a model to verify it before benchmarking. The endpoint and headers come from the agent's stored config; a successful check is recorded on the agent.
`,
  scopes: ["write"],
  annotations: {
    "title": "Verify agent connection",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsVerifyConnection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
