/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsRun } from "../../funcs/agentTestsRun.js";
import { RunAgentTestAgentTestsAgentAgentUuidRunPostRequest$zodSchema } from "../../models/runagenttestagenttestsagentagentuuidrunpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RunAgentTestAgentTestsAgentAgentUuidRunPostRequest$zodSchema,
};

export const tool$agentTestsRun: ToolDefinition<typeof args> = {
  name: "run-agent-tests",
  description:
    `Start a background LLM unit-test job for one agent. Runs all tests
linked to the agent unless test_uuids is provided. Returns a task_id
to poll with get-agent-test-run. The agent must belong to the caller's
org and have a verified connection; otherwise the call fails with 400
or 404.
`,
  scopes: ["write"],
  annotations: {
    "title": "Run agent tests",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsRun(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
