/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsCreate } from "../../funcs/agentsCreate.js";
import { CreateAgentEndpointAgentsPostRequest$zodSchema } from "../../models/createagentendpointagentspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAgentEndpointAgentsPostRequest$zodSchema,
};

export const tool$agentsCreate: ToolDefinition<typeof args> = {
  name: "create-agent",
  description:
    `Create a new agent in the caller's organization. Provide the agent's
name, type, and config. Returns the created agent including its UUID.
Requires a Calibrate API key (CALIBRATE_API_KEY).
`,
  scopes: ["write"],
  annotations: {
    "title": "Create agent",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
