/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsListRunsForAgent } from "../../funcs/agentTestsListRunsForAgent.js";
import { GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetRequest$zodSchema } from "../../models/getagenttestrunsagenttestsagentagentuuidrunsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetRequest$zodSchema,
};

export const tool$agentTestsListRunsForAgent: ToolDefinition<typeof args> = {
  name: "list-agent-test-runs",
  description:
    `List an agent's test and benchmark runs, most recently created first, with their status and results.
`,
  scopes: ["read"],
  annotations: {
    "title": "List test runs for an agent",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsListRunsForAgent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
