/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsLink } from "../../funcs/agentTestsLink.js";
import { CreateAgentTestLinksAgentTestsPostRequest$zodSchema } from "../../models/createagenttestlinksagenttestspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAgentTestLinksAgentTestsPostRequest$zodSchema,
};

export const tool$agentTestsLink: ToolDefinition<typeof args> = {
  name: "link-tests-to-agent",
  description:
    `Link one or more existing tests to an agent so they run together. Tests already linked are skipped. The agent and every test must be in your workspace.
`,
  scopes: ["write"],
  annotations: {
    "title": "Link tests to agent",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsLink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
