/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsUpdate } from "../../funcs/agentsUpdate.js";
import { UpdateAgentEndpointAgentsAgentUuidPutRequest$zodSchema } from "../../models/updateagentendpointagentsagentuuidputop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateAgentEndpointAgentsAgentUuidPutRequest$zodSchema,
};

export const tool$agentsUpdate: ToolDefinition<typeof args> = {
  name: "update-agent",
  description:
    `Update an existing agent by UUID within the caller's org. Supply the
fields to change (name, type, config). Returns the updated agent.
Fails with 404 if the agent does not exist or belongs to another org.
`,
  scopes: ["write"],
  annotations: {
    "title": "Update agent",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
