/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsList } from "../../funcs/agentsList.js";
import { ListAgentsAgentsGetRequest$zodSchema } from "../../models/listagentsagentsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAgentsAgentsGetRequest$zodSchema.optional(),
};

export const tool$agentsList: ToolDefinition<typeof args> = {
  name: "list-agents",
  description:
    `List every agent in the caller's organization. Returns each agent's
UUID, name, type, and config. Use this to discover which agents exist
before resolving names or launching test runs. Requires a Calibrate
API key (CALIBRATE_API_KEY).
`,
  scopes: ["read"],
  annotations: {
    "title": "List agents",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
