/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsGetRun } from "../../funcs/agentTestsGetRun.js";
import { GetAgentTestRunStatusAgentTestsRunTaskIdGetRequest$zodSchema } from "../../models/getagenttestrunstatusagenttestsruntaskidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentTestRunStatusAgentTestsRunTaskIdGetRequest$zodSchema,
};

export const tool$agentTestsGetRun: ToolDefinition<typeof args> = {
  name: "get-agent-test-run",
  description:
    `Poll the status and results of an agent test run by task_id. Returns
queued, in_progress, completed, failed, or aborted status. When
completed, includes per-test-case pass/fail results and evaluator
judgments. Use the task_id from run-agent-tests or
run-agent-tests-batch.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get agent test run status",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsGetRun(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
