/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsRunBatch } from "../../funcs/agentTestsRunBatch.js";
import { RunTestsBatchAgentTestsRunPostRequest$zodSchema } from "../../models/runtestsbatchagenttestsrunpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RunTestsBatchAgentTestsRunPostRequest$zodSchema.optional(),
};

export const tool$agentTestsRunBatch: ToolDefinition<typeof args> = {
  name: "run-agent-tests-batch",
  description:
    `Launch one test job per agent in the caller's org. Optionally restrict
to agent_names; omit or pass an empty list to run every org agent.
Agents with no linked tests or an unverified connection are skipped
(reported under skipped) rather than failing the batch. Returns
task_id values to poll with get-agent-test-run.
`,
  scopes: ["write"],
  annotations: {
    "title": "Run agent tests (batch)",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsRunBatch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
