/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsLinkEvaluators } from "../../funcs/agentsLinkEvaluators.js";
import { LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest$zodSchema } from "../../models/linkevaluatorstoagentagentsagentuuidevaluatorspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest$zodSchema,
};

export const tool$agentsLinkEvaluators: ToolDefinition<typeof args> = {
  name: "link-evaluators-to-agent",
  description:
    `Link one or more evaluators to an agent, skipping any already linked.
Each evaluator must be one you created or a built-in default, and the
agent must be in your workspace.
`,
  scopes: ["write"],
  annotations: {
    "title": "Link evaluators to an agent",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsLinkEvaluators(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
