/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsListEvaluators } from "../../funcs/agentsListEvaluators.js";
import { ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetRequest$zodSchema } from "../../models/listagentevaluatorsagentsagentuuidevaluatorsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetRequest$zodSchema,
};

export const tool$agentsListEvaluators: ToolDefinition<typeof args> = {
  name: "list-agent-evaluators",
  description:
    `List the evaluators linked to an agent, most recently linked first.
Returns each evaluator's UUID, name, type, and live version summary.
`,
  scopes: ["read"],
  annotations: {
    "title": "List evaluators linked to an agent",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsListEvaluators(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
