/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsResolve } from "../../funcs/agentsResolve.js";
import { ResolveAgentNamesAgentsResolvePostRequest$zodSchema } from "../../models/resolveagentnamesagentsresolvepostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ResolveAgentNamesAgentsResolvePostRequest$zodSchema,
};

export const tool$agentsResolve: ToolDefinition<typeof args> = {
  name: "resolve-agent-names",
  description:
    `Map human-friendly agent names to UUIDs within the caller's org. Each
name resolves to at most one agent; unknown names are returned under
not_found. Use this before run-agent-tests when you have names instead
of UUIDs. Does not create or modify agents.
`,
  scopes: ["read"],
  annotations: {
    "title": "Resolve agent names to UUIDs",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsResolve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
