/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsBulkUnlink } from "../../funcs/agentTestsBulkUnlink.js";
import { BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest$zodSchema } from "../../models/bulkdeleteagenttestlinksagenttestsbulkunlinkpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest$zodSchema,
};

export const tool$agentTestsBulkUnlink: ToolDefinition<typeof args> = {
  name: "bulk-unlink-agent-tests",
  description:
    `Remove one or more tests from an agent in a single call. The tests
themselves are kept and stay available to other agents; only the links
to this agent go. Tests that were not linked are skipped, so
deleted_count can be lower than the number of ids sent. Fails with 404
when the agent is not in the caller's org and 400 when test_uuids is
empty.
`,
  scopes: ["write"],
  annotations: {
    "title": "Unlink tests from an agent",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsBulkUnlink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
