/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsListForAgent } from "../../funcs/agentTestsListForAgent.js";
import { GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest$zodSchema } from "../../models/getagenttestsendpointagenttestsagentagentuuidtestsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest$zodSchema,
};

export const tool$agentTestsListForAgent: ToolDefinition<typeof args> = {
  name: "list-agent-tests",
  description: `List the tests linked to an agent.
`,
  scopes: ["read"],
  annotations: {
    "title": "List tests for an agent",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsListForAgent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
