/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGet } from "../../funcs/agentsGet.js";
import { GetAgentEndpointAgentsAgentUuidGetRequest$zodSchema } from "../../models/getagentendpointagentsagentuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentEndpointAgentsAgentUuidGetRequest$zodSchema,
};

export const tool$agentsGet: ToolDefinition<typeof args> = {
  name: "get-agent",
  description:
    `Fetch a single agent by UUID within the caller's org. Returns the
agent's name, type, and config. Fails with 404 if the agent does not
exist or belongs to another org.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get agent",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
