/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTestsGetRunCase } from "../../funcs/agentTestsGetRunCase.js";
import { GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetRequest$zodSchema } from "../../models/getagenttestcaseresultagenttestsruntaskidresultstestuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetRequest$zodSchema,
};

export const tool$agentTestsGetRunCase: ToolDefinition<typeof args> = {
  name: "get-agent-test-case-result",
  description: `Fetch the full result of one test case in a run, including the
conversation, the agent's output and each evaluator's reasoning. Pass
the model query param for a benchmark, which runs every test once per
model. Use with mode=summary on get-agent-test-run, which returns
light rows without this detail.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get agent test case result",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTestsGetRunCase(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
