/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotatorsUpdate } from "../../funcs/annotatorsUpdate.js";
import { UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutRequest$zodSchema } from "../../models/updateannotatorendpointannotatorsannotatoruuidputop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutRequest$zodSchema,
};

export const tool$annotatorsUpdate: ToolDefinition<typeof args> = {
  name: "update-annotator",
  description: `Rename an annotator in your workspace.
`,
  scopes: ["write"],
  annotations: {
    "title": "Update annotator",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotatorsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
