/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksAddItems } from "../../funcs/annotationTasksAddItems.js";
import { BulkCreateItemsAnnotationTasksTaskUuidItemsPostRequest$zodSchema } from "../../models/bulkcreateitemsannotationtaskstaskuuiditemspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkCreateItemsAnnotationTasksTaskUuidItemsPostRequest$zodSchema,
};

export const tool$annotationTasksAddItems: ToolDefinition<typeof args> = {
  name: "add-annotation-items",
  description:
    `Bulk-create items in an annotation task, optionally seeding human annotations.
`,
  scopes: ["write"],
  annotations: {
    "title": "Bulk create items",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksAddItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
