/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksSetEvaluators } from "../../funcs/annotationTasksSetEvaluators.js";
import { SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutRequest$zodSchema } from "../../models/settaskevaluatorsannotationtaskstaskuuidevaluatorsputop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutRequest$zodSchema,
};

export const tool$annotationTasksSetEvaluators: ToolDefinition<typeof args> = {
  name: "set-task-evaluators",
  description:
    `Replace the task's linked evaluators with exactly the given ordered
set: new ids are linked, omitted ids are unlinked, and the list order
sets their display position. Send an empty list to unlink all. Each
evaluator must be one you created or a built-in default, and the task
must be in your workspace.
`,
  scopes: ["write"],
  annotations: {
    "title": "Set an annotation task's evaluators",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksSetEvaluators(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
