/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksGetEvaluatorRun } from "../../funcs/annotationTasksGetEvaluatorRun.js";
import {
  GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetRequest$zodSchema,
} from "../../models/getevaluatorrunjobannotationtaskstaskuuidevaluatorrunsjobuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetRequest$zodSchema,
};

export const tool$annotationTasksGetEvaluatorRun: ToolDefinition<typeof args> =
  {
    name: "get-annotation-evaluator-run",
    description:
      `Get one evaluator-run job with its results and human-agreement summary.
`,
    scopes: ["read"],
    annotations: {
      "title": "Get evaluator run",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await annotationTasksGetEvaluatorRun(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
