/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksList } from "../../funcs/annotationTasksList.js";
import { ListAnnotationTasksAnnotationTasksGetRequest$zodSchema } from "../../models/listannotationtasksannotationtasksgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAnnotationTasksAnnotationTasksGetRequest$zodSchema.optional(),
};

export const tool$annotationTasksList: ToolDefinition<typeof args> = {
  name: "list-annotation-tasks",
  description: `List your annotation tasks with their linked evaluators.
`,
  scopes: ["read"],
  annotations: {
    "title": "List annotation tasks",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
