/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksLinkEvaluator } from "../../funcs/annotationTasksLinkEvaluator.js";
import { LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostRequest$zodSchema } from "../../models/linkevaluatortotaskannotationtaskstaskuuidevaluatorspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostRequest$zodSchema,
};

export const tool$annotationTasksLinkEvaluator: ToolDefinition<typeof args> = {
  name: "link-evaluator-to-task",
  description:
    `Link an evaluator to an annotation task, appending it to the display order.
`,
  scopes: ["write"],
  annotations: {
    "title": "Link evaluator to task",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksLinkEvaluator(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
