/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksCreateEvaluatorRun } from "../../funcs/annotationTasksCreateEvaluatorRun.js";
import { StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostRequest$zodSchema } from "../../models/startevaluatorrunannotationtaskstaskuuidevaluatorrunspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostRequest$zodSchema,
};

export const tool$annotationTasksCreateEvaluatorRun: ToolDefinition<
  typeof args
> = {
  name: "run-annotation-evaluators",
  description:
    `Run one or more of a task's evaluators over its items as a background job. Returns a job_uuid to poll with get-annotation-evaluator-run.
`,
  scopes: ["write"],
  annotations: {
    "title": "Run evaluators on items",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksCreateEvaluatorRun(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
