/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksUpdateItems } from "../../funcs/annotationTasksUpdateItems.js";
import { BulkUpdateItemsAnnotationTasksTaskUuidItemsPutRequest$zodSchema } from "../../models/bulkupdateitemsannotationtaskstaskuuiditemsputop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkUpdateItemsAnnotationTasksTaskUuidItemsPutRequest$zodSchema,
};

export const tool$annotationTasksUpdateItems: ToolDefinition<typeof args> = {
  name: "update-annotation-items",
  description: `Bulk-update item payloads in an annotation task.
`,
  scopes: ["write"],
  annotations: {
    "title": "Bulk update items",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksUpdateItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
