/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksGetSummary } from "../../funcs/annotationTasksGetSummary.js";
import { TaskSummaryAnnotationTasksTaskUuidSummaryGetRequest$zodSchema } from "../../models/tasksummaryannotationtaskstaskuuidsummarygetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TaskSummaryAnnotationTasksTaskUuidSummaryGetRequest$zodSchema,
};

export const tool$annotationTasksGetSummary: ToolDefinition<typeof args> = {
  name: "get-annotation-summary",
  description:
    `Get a paginated summary table for a task, with each item's evaluator values and human labels.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get task summary",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksGetSummary(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
