/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksGetAgreement } from "../../funcs/annotationTasksGetAgreement.js";
import { TaskAgreementAnnotationTasksTaskUuidAgreementGetRequest$zodSchema } from "../../models/taskagreementannotationtaskstaskuuidagreementgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TaskAgreementAnnotationTasksTaskUuidAgreementGetRequest$zodSchema,
};

export const tool$annotationTasksGetAgreement: ToolDefinition<typeof args> = {
  name: "get-annotation-agreement",
  description:
    `Get human-vs-human and human-vs-evaluator agreement metrics for a task, with a trend series.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get task agreement",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksGetAgreement(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
