/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotatorsList } from "../../funcs/annotatorsList.js";
import { ListAnnotatorsAnnotatorsGetRequest$zodSchema } from "../../models/listannotatorsannotatorsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAnnotatorsAnnotatorsGetRequest$zodSchema.optional(),
};

export const tool$annotatorsList: ToolDefinition<typeof args> = {
  name: "list-annotators",
  description: `List your annotators with their job counts and agreement scores.
`,
  scopes: ["read"],
  annotations: {
    "title": "List annotators",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotatorsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
