/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksGet } from "../../funcs/annotationTasksGet.js";
import { GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetRequest$zodSchema } from "../../models/getannotationtaskendpointannotationtaskstaskuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetRequest$zodSchema,
};

export const tool$annotationTasksGet: ToolDefinition<typeof args> = {
  name: "get-annotation-task",
  description:
    `Get one annotation task with its evaluators, items, and labelling jobs.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get annotation task",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
