/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotatorsCreate } from "../../funcs/annotatorsCreate.js";
import { CreateAnnotatorEndpointAnnotatorsPostRequest$zodSchema } from "../../models/createannotatorendpointannotatorspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAnnotatorEndpointAnnotatorsPostRequest$zodSchema,
};

export const tool$annotatorsCreate: ToolDefinition<typeof args> = {
  name: "create-annotator",
  description:
    `Create an annotator, a human labeller who can be assigned annotation tasks.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create annotator",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotatorsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
