/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksCreate } from "../../funcs/annotationTasksCreate.js";
import { CreateAnnotationTaskEndpointAnnotationTasksPostRequest$zodSchema } from "../../models/createannotationtaskendpointannotationtaskspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAnnotationTaskEndpointAnnotationTasksPostRequest$zodSchema,
};

export const tool$annotationTasksCreate: ToolDefinition<typeof args> = {
  name: "create-annotation-task",
  description:
    `Create an annotation task for labelling items against evaluators. Optionally link evaluators in order.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create annotation task",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
