/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { annotationTasksCreateLabellingJobs } from "../../funcs/annotationTasksCreateLabellingJobs.js";
import { CreateJobsAnnotationTasksTaskUuidJobsPostRequest$zodSchema } from "../../models/createjobsannotationtaskstaskuuidjobspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateJobsAnnotationTasksTaskUuidJobsPostRequest$zodSchema,
};

export const tool$annotationTasksCreateLabellingJobs: ToolDefinition<
  typeof args
> = {
  name: "create-labelling-jobs",
  description:
    `Assign items to annotators, creating one labelling job per annotator. Each job comes back with a public_token for the annotator's labelling link.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create labelling jobs",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await annotationTasksCreateLabellingJobs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
