/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evaluatorsCreate } from "../../funcs/evaluatorsCreate.js";
import { CreateEvaluatorEndpointEvaluatorsPostRequest$zodSchema } from "../../models/createevaluatorendpointevaluatorspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateEvaluatorEndpointEvaluatorsPostRequest$zodSchema,
};

export const tool$evaluatorsCreate: ToolDefinition<typeof args> = {
  name: "create-evaluator",
  description:
    `Create an evaluator and its first version, which is set live. An evaluator judges an output against a prompt and rubric.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create evaluator",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await evaluatorsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
