/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evaluatorsCreateVersion } from "../../funcs/evaluatorsCreateVersion.js";
import { CreateVersionEvaluatorsEvaluatorUuidVersionsPostRequest$zodSchema } from "../../models/createversionevaluatorsevaluatoruuidversionspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateVersionEvaluatorsEvaluatorUuidVersionsPostRequest$zodSchema,
};

export const tool$evaluatorsCreateVersion: ToolDefinition<typeof args> = {
  name: "create-evaluator-version",
  description:
    `Add a new version to an evaluator you created, optionally making it live. The variable names must match the previous version.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create evaluator version",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await evaluatorsCreateVersion(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
