/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evaluatorsGet } from "../../funcs/evaluatorsGet.js";
import { GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetRequest$zodSchema } from "../../models/getevaluatorendpointevaluatorsevaluatoruuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetRequest$zodSchema,
};

export const tool$evaluatorsGet: ToolDefinition<typeof args> = {
  name: "get-evaluator",
  description: `Get one evaluator with its full version history.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get evaluator",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await evaluatorsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
