/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evaluatorsList } from "../../funcs/evaluatorsList.js";
import { ListEvaluatorsEvaluatorsGetRequest$zodSchema } from "../../models/listevaluatorsevaluatorsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListEvaluatorsEvaluatorsGetRequest$zodSchema.optional(),
};

export const tool$evaluatorsList: ToolDefinition<typeof args> = {
  name: "list-evaluators",
  description:
    `List your evaluators. Optionally filter by what they judge or their modality, and include the built-in defaults.
`,
  scopes: ["read"],
  annotations: {
    "title": "List evaluators",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await evaluatorsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
