/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testsBulkCreate } from "../../funcs/testsBulkCreate.js";
import { BulkUploadTestsTestsBulkPostRequest$zodSchema } from "../../models/bulkuploadteststestsbulkpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkUploadTestsTestsBulkPostRequest$zodSchema,
};

export const tool$testsBulkCreate: ToolDefinition<typeof args> = {
  name: "bulk-create-tests",
  description:
    `Create multiple tests in the caller's organization in one call. Provide
a list of test definitions (name, type, config). Returns the created
tests including their UUIDs.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create tests (bulk)",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await testsBulkCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
