/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testsGet } from "../../funcs/testsGet.js";
import { GetTestEndpointTestsTestUuidGetRequest$zodSchema } from "../../models/gettestendpointteststestuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTestEndpointTestsTestUuidGetRequest$zodSchema,
};

export const tool$testsGet: ToolDefinition<typeof args> = {
  name: "get-test",
  description: `Fetch a single test by UUID within the caller's org. Returns the
test's name, type, and config. Fails with 404 if the test does not
exist or belongs to another org.
`,
  scopes: ["read"],
  annotations: {
    "title": "Get test",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await testsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
