/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testsCreate } from "../../funcs/testsCreate.js";
import { CreateTestEndpointTestsPostRequest$zodSchema } from "../../models/createtestendpointtestspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateTestEndpointTestsPostRequest$zodSchema,
};

export const tool$testsCreate: ToolDefinition<typeof args> = {
  name: "create-test",
  description:
    `Create a new test in the caller's organization. Provide the test's
name, type, and config. Returns the created test including its UUID.
Requires a Calibrate API key (CALIBRATE_API_KEY).
`,
  scopes: ["write"],
  annotations: {
    "title": "Create test",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await testsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
