/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testsList } from "../../funcs/testsList.js";
import { ListTestsTestsGetRequest$zodSchema } from "../../models/listteststestsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTestsTestsGetRequest$zodSchema.optional(),
};

export const tool$testsList: ToolDefinition<typeof args> = {
  name: "list-tests",
  description:
    `List every test in the caller's organization. Returns each test's
UUID, name, type, and config. Use this to discover which tests exist
before creating runs.
`,
  scopes: ["read"],
  annotations: {
    "title": "List tests",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await testsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
