/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testsUpdate } from "../../funcs/testsUpdate.js";
import { UpdateTestEndpointTestsTestUuidPutRequest$zodSchema } from "../../models/updatetestendpointteststestuuidputop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTestEndpointTestsTestUuidPutRequest$zodSchema,
};

export const tool$testsUpdate: ToolDefinition<typeof args> = {
  name: "update-test",
  description:
    `Update an existing test by UUID within the caller's org. Supply the
fields to change (name, config). Returns the updated test. Fails with
404 if the test does not exist or belongs to another org.
`,
  scopes: ["write"],
  annotations: {
    "title": "Update test",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await testsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
