/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tracesCreate } from "../../funcs/tracesCreate.js";
import { IngestTraceTracesPostRequest$zodSchema } from "../../models/ingesttracetracespostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IngestTraceTracesPostRequest$zodSchema,
};

export const tool$tracesCreate: ToolDefinition<typeof args> = {
  name: "create-trace",
  description:
    `Store one production agent turn against an agent in the caller's org:
the conversation history as input, what the agent produced as output,
and optional metadata. Use this to capture live traffic for later
review and conversion into tests. Fails with 429 once the workspace
hits its trace limit.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create trace",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tracesCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
