/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentTestsBulkUnlinkResponse = {
  deleted_count: number;
  message: string;
};

export const AgentTestsBulkUnlinkResponse$zodSchema: z.ZodType<
  AgentTestsBulkUnlinkResponse
> = z.object({
  deleted_count: z.int().describe(
    "Number of links removed. Tests that were not linked are excluded",
  ),
  message: z.string().describe("Confirmation message"),
});
