/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export const AgentSummaryType = {
  Agent: "agent",
  Connection: "connection",
} as const;
/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export type AgentSummaryType = ClosedEnum<typeof AgentSummaryType>;

export const AgentSummaryType$zodSchema = z.enum([
  "agent",
  "connection",
]).describe(
  "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
);

export type AgentSummary = {
  uuid: string;
  name: string;
  type: AgentSummaryType;
  updated_at: string;
  connection_verified?: boolean | null | undefined;
};

export const AgentSummary$zodSchema: z.ZodType<AgentSummary> = z.object({
  connection_verified: z.boolean().nullable().optional().describe(
    "Whether the agent's connection has been verified, for a `type=connection` agent",
  ),
  name: z.string().describe("Name of the agent"),
  type: AgentSummaryType$zodSchema.describe(
    "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
  ),
  updated_at: z.string().describe(
    "When the agent was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("ID of the agent"),
});
