/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentTestBulkDelete = {
  agent_uuid: string;
  test_uuids: Array<string>;
};

export const AgentTestBulkDelete$zodSchema: z.ZodType<AgentTestBulkDelete> = z
  .object({
    agent_uuid: z.string().describe("Agent to unlink tests from"),
    test_uuids: z.array(z.string()).describe("Tests to unlink from the agent"),
  });
