/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentCreateResponse = { uuid: string; message: string };

export const AgentCreateResponse$zodSchema: z.ZodType<AgentCreateResponse> = z
  .object({
    message: z.string().describe("Confirmation message"),
    uuid: z.string().describe("ID of the newly created agent"),
  });
