/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentTestsCreate = {
  agent_uuid: string;
  test_uuids: Array<string>;
};

export const AgentTestsCreate$zodSchema: z.ZodType<AgentTestsCreate> = z.object(
  {
    agent_uuid: z.string().describe("Agent to link tests to"),
    test_uuids: z.array(z.string()).describe(
      "Tests to link. Any that are already linked are skipped",
    ),
  },
);
