/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Body for verifying an existing agent by ID. The endpoint (`agent_url`,
 *
 * @remarks
 * `agent_headers`) comes from the agent's stored config, so only the probe
 * inputs are accepted here.
 */
export type AgentVerifyRequest = {
  model?: string | null | undefined;
  messages?: Array<{ [k: string]: string }> | null | undefined;
};

export const AgentVerifyRequest$zodSchema: z.ZodType<AgentVerifyRequest> = z
  .object({
    messages: z.array(z.record(z.string(), z.string())).nullable().optional()
      .describe(
        "Sample chat messages to send during verification. Omit to use the default probe",
      ),
    model: z.string().nullable().optional().describe(
      "Model to verify. Omit for a basic connection check. Provide it for a model-specific check before benchmarking that model",
    ),
  }).describe(
    "Body for verifying an existing agent by ID. The endpoint (`agent_url`,\n`agent_headers`) comes from the agent's stored config, so only the probe\ninputs are accepted here.",
  );
