/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ModelRunSummary,
  ModelRunSummary$zodSchema,
} from "./modelrunsummary.js";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";
import {
  TestRunCaseSummary,
  TestRunCaseSummary$zodSchema,
} from "./testruncasesummary.js";

/**
 * What kind of run this is:
 *
 * @remarks
 * - `llm-unit-test`: a single run of the agent's tests
 * - `llm-benchmark`: a multi-model comparison
 */
export const AgentTestRunListItemType = {
  LlmUnitTest: "llm-unit-test",
  LlmBenchmark: "llm-benchmark",
} as const;
/**
 * What kind of run this is:
 *
 * @remarks
 * - `llm-unit-test`: a single run of the agent's tests
 * - `llm-benchmark`: a multi-model comparison
 */
export type AgentTestRunListItemType = ClosedEnum<
  typeof AgentTestRunListItemType
>;

export const AgentTestRunListItemType$zodSchema = z.enum([
  "llm-unit-test",
  "llm-benchmark",
]).describe(
  "What kind of run this is:\n- `llm-unit-test`: a single run of the agent's tests\n- `llm-benchmark`: a multi-model comparison",
);

export type AgentTestRunListItem = {
  uuid: string;
  name: string;
  status: TaskStatus;
  type: AgentTestRunListItemType;
  updated_at: string;
  total_tests?: number | null | undefined;
  passed?: number | null | undefined;
  failed?: number | null | undefined;
  results?: Array<TestRunCaseSummary> | null | undefined;
  latency_ms?: { [k: string]: any } | null | undefined;
  cost?: { [k: string]: any } | null | undefined;
  total_tokens?: { [k: string]: any } | null | undefined;
  model_results?: Array<ModelRunSummary> | null | undefined;
  error?: boolean | undefined;
  is_public?: boolean | undefined;
  share_token?: string | null | undefined;
};

export const AgentTestRunListItem$zodSchema: z.ZodType<AgentTestRunListItem> = z
  .object({
    cost: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated cost as `{mean, min, max, count}` (USD)",
    ),
    error: z.boolean().default(false).describe("True if the run failed"),
    failed: z.int().nullable().optional().describe(
      "Number of test cases that failed",
    ),
    is_public: z.boolean().default(false).describe(
      "Whether the run is shared publicly",
    ),
    latency_ms: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated latency in milliseconds, as `{p50, p95, p99, count}`",
    ),
    model_results: z.array(ModelRunSummary$zodSchema).nullable().optional()
      .describe(
        "Flat summary for each model in a benchmark run (fetch the benchmark detail for full results)",
      ),
    name: z.string().describe(
      "Display name, such as `Run 1` for a unit test or `Benchmark 1` for a benchmark",
    ),
    passed: z.int().nullable().optional().describe(
      "Number of test cases that passed",
    ),
    results: z.array(TestRunCaseSummary$zodSchema).nullable().optional()
      .describe(
        "Flat pass/fail summary for each test case (fetch the run detail for full results)",
      ),
    share_token: z.string().nullable().optional().describe(
      "Token for building the public share URL",
    ),
    status: TaskStatus$zodSchema,
    total_tests: z.int().nullable().optional().describe(
      "Total number of test cases",
    ),
    total_tokens: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated token usage as `{mean, min, max, count}`",
    ),
    type: AgentTestRunListItemType$zodSchema.describe(
      "What kind of run this is:\n- `llm-unit-test`: a single run of the agent's tests\n- `llm-benchmark`: a multi-model comparison",
    ),
    updated_at: z.string().describe(
      "When the run was last updated (ISO 8601 UTC)",
    ),
    uuid: z.string().describe("Test run job ID"),
  });
