/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ModelResult, ModelResult$zodSchema } from "./modelresult.js";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";
import { TestCaseResult, TestCaseResult$zodSchema } from "./testcaseresult.js";
import {
  TestRunEvaluator,
  TestRunEvaluator$zodSchema,
} from "./testrunevaluator.js";

/**
 * What kind of run this is:
 *
 * @remarks
 * - `llm-unit-test`: a single run of the agent's tests
 * - `llm-benchmark`: a multi-model comparison
 */
export const AgentTestRunListItemType = {
  LlmUnitTest: "llm-unit-test",
  LlmBenchmark: "llm-benchmark",
} as const;
/**
 * What kind of run this is:
 *
 * @remarks
 * - `llm-unit-test`: a single run of the agent's tests
 * - `llm-benchmark`: a multi-model comparison
 */
export type AgentTestRunListItemType = ClosedEnum<
  typeof AgentTestRunListItemType
>;

export const AgentTestRunListItemType$zodSchema = z.enum([
  "llm-unit-test",
  "llm-benchmark",
]).describe(
  "What kind of run this is:\n- `llm-unit-test`: a single run of the agent's tests\n- `llm-benchmark`: a multi-model comparison",
);

export type AgentTestRunListItem = {
  uuid: string;
  name: string;
  status: TaskStatus;
  type: AgentTestRunListItemType;
  updated_at: string;
  evaluators?: Array<TestRunEvaluator> | null | undefined;
  total_tests?: number | null | undefined;
  passed?: number | null | undefined;
  failed?: number | null | undefined;
  results?: Array<TestCaseResult> | null | undefined;
  latency_ms?: { [k: string]: any } | null | undefined;
  cost?: { [k: string]: any } | null | undefined;
  total_tokens?: { [k: string]: any } | null | undefined;
  model_results?: Array<ModelResult> | null | undefined;
  leaderboard_summary?: Array<{ [k: string]: any }> | null | undefined;
  error?: boolean | undefined;
  is_public?: boolean | undefined;
  share_token?: string | null | undefined;
};

export const AgentTestRunListItem$zodSchema: z.ZodType<AgentTestRunListItem> = z
  .object({
    cost: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated cost as `{mean, min, max, count}` (USD)",
    ),
    error: z.boolean().default(false).describe("True if the run failed"),
    evaluators: z.array(TestRunEvaluator$zodSchema).nullable().optional()
      .describe(
        "The evaluators used in this run. Each verdict in `judge_results` links to one of these by `evaluator_uuid`",
      ),
    failed: z.int().nullable().optional().describe(
      "Number of test cases that failed",
    ),
    is_public: z.boolean().default(false).describe(
      "Whether the run is shared publicly",
    ),
    latency_ms: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated latency in milliseconds, as `{p50, p95, p99, count}`",
    ),
    leaderboard_summary: z.array(z.record(z.string(), z.any())).nullable()
      .optional().describe(
        "Leaderboard comparing the models, one row per model. Columns vary by benchmark: a `model` column plus pass/fail counts, latency, cost, and one score column per evaluator, keyed by evaluator name",
      ),
    model_results: z.array(ModelResult$zodSchema).nullable().optional()
      .describe("Results for each model in a benchmark run"),
    name: z.string().describe(
      "Display name, such as `Run 1` for a unit test or `Benchmark 1` for a benchmark",
    ),
    passed: z.int().nullable().optional().describe(
      "Number of test cases that passed",
    ),
    results: z.array(TestCaseResult$zodSchema).nullable().optional().describe(
      "Results for each test case",
    ),
    share_token: z.string().nullable().optional().describe(
      "Token for building the public share URL",
    ),
    status: TaskStatus$zodSchema,
    total_tests: z.int().nullable().optional().describe(
      "Total number of test cases",
    ),
    total_tokens: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated token usage as `{mean, min, max, count}`",
    ),
    type: AgentTestRunListItemType$zodSchema.describe(
      "What kind of run this is:\n- `llm-unit-test`: a single run of the agent's tests\n- `llm-benchmark`: a multi-model comparison",
    ),
    updated_at: z.string().describe(
      "When the run was last updated (ISO 8601 UTC)",
    ),
    uuid: z.string().describe("Test run job ID"),
  });
