/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestRunListItem,
  AgentTestRunListItem$zodSchema,
} from "./agenttestrunlistitem.js";

export type AgentTestRunsResponse = { runs: Array<AgentTestRunListItem> };

export const AgentTestRunsResponse$zodSchema: z.ZodType<AgentTestRunsResponse> =
  z.object({
    runs: z.array(AgentTestRunListItem$zodSchema).describe(
      "Test runs for the agent, most recently created first",
    ),
  });
