/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentTestsCreateResponse = { message: string };

export const AgentTestsCreateResponse$zodSchema: z.ZodType<
  AgentTestsCreateResponse
> = z.object({
  message: z.string().describe("Confirmation message"),
});
