/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Current status of the run
 */
export const AgentTestRunCreateResponseStatus = {
  Queued: "queued",
  InProgress: "in_progress",
} as const;
/**
 * Current status of the run
 */
export type AgentTestRunCreateResponseStatus = ClosedEnum<
  typeof AgentTestRunCreateResponseStatus
>;

export const AgentTestRunCreateResponseStatus$zodSchema = z.enum([
  "queued",
  "in_progress",
]).describe("Current status of the run");

export type AgentTestRunCreateResponse = {
  task_id: string;
  status: AgentTestRunCreateResponseStatus;
};

export const AgentTestRunCreateResponse$zodSchema: z.ZodType<
  AgentTestRunCreateResponse
> = z.object({
  status: AgentTestRunCreateResponseStatus$zodSchema.describe(
    "Current status of the run",
  ),
  task_id: z.string().describe(
    "Test run job ID. Poll it for status and results",
  ),
});
