/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export const AgentResponseType = {
  Agent: "agent",
  Connection: "connection",
} as const;
/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export type AgentResponseType = ClosedEnum<typeof AgentResponseType>;

export const AgentResponseType$zodSchema = z.enum([
  "agent",
  "connection",
]).describe(
  "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
);

/**
 * What the agent expects in the request body:
 *
 * @remarks
 *
 * - `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{"messages": [...]}`
 * - `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{"input": "..."}`
 */
export const AgentResponseInteractionType = {
  Conversation: "conversation",
  General: "general",
} as const;
/**
 * What the agent expects in the request body:
 *
 * @remarks
 *
 * - `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{"messages": [...]}`
 * - `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{"input": "..."}`
 */
export type AgentResponseInteractionType = ClosedEnum<
  typeof AgentResponseInteractionType
>;

export const AgentResponseInteractionType$zodSchema = z.enum([
  "conversation",
  "general",
]).describe(
  "What the agent expects in the request body:\n\n- `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{\"messages\": [...]}`\n- `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{\"input\": \"...\"}`",
);

export type AgentResponse = {
  uuid: string;
  name: string;
  type: AgentResponseType;
  interaction_type: AgentResponseInteractionType;
  config?: { [k: string]: any } | null | undefined;
  created_at: string;
  updated_at: string;
};

export const AgentResponse$zodSchema: z.ZodType<AgentResponse> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "Agent configuration",
  ),
  created_at: z.string().describe("When the agent was created (ISO 8601 UTC)"),
  interaction_type: AgentResponseInteractionType$zodSchema.describe(
    "What the agent expects in the request body:\n\n- `conversation`: a normal back-and-forth agent, answers within an ongoing conversation. Receives `{\"messages\": [...]}`\n- `general`: a one-shot agent, takes a single plain input and produces a single plain output, no conversation. Receives `{\"input\": \"...\"}`",
  ),
  name: z.string().describe("Name of the agent"),
  type: AgentResponseType$zodSchema.describe(
    "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
  ),
  updated_at: z.string().describe(
    "When the agent was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("ID of the agent"),
});
