/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotatorCreateResponse = { uuid: string; message: string };

export const AnnotatorCreateResponse$zodSchema: z.ZodType<
  AnnotatorCreateResponse
> = z.object({
  message: z.string().describe("Success message"),
  uuid: z.string().describe("ID of the newly created annotator"),
});
