/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Task type. Determines the shape of each item's payload.
 *
 * @remarks
 * - `stt`: judge a transcript on its own
 * - `llm`: judge one response with its conversation history
 * - `llm-general`: judge a standalone `input -> output` pair
 * - `conversation`: judge a full conversation
 */
export const AnnotationTaskCreateType = {
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
  Tts: "tts",
} as const;
/**
 * Task type. Determines the shape of each item's payload.
 *
 * @remarks
 * - `stt`: judge a transcript on its own
 * - `llm`: judge one response with its conversation history
 * - `llm-general`: judge a standalone `input -> output` pair
 * - `conversation`: judge a full conversation
 */
export type AnnotationTaskCreateType = ClosedEnum<
  typeof AnnotationTaskCreateType
>;

export const AnnotationTaskCreateType$zodSchema = z.enum([
  "stt",
  "llm",
  "llm-general",
  "conversation",
  "tts",
]).describe(
  "Task type. Determines the shape of each item's payload.\n- `stt`: judge a transcript on its own\n- `llm`: judge one response with its conversation history\n- `llm-general`: judge a standalone `input -> output` pair\n- `conversation`: judge a full conversation",
);

export type AnnotationTaskCreate = {
  name: string;
  type: AnnotationTaskCreateType;
  description?: string | null | undefined;
  evaluator_ids?: Array<string> | null | undefined;
};

export const AnnotationTaskCreate$zodSchema: z.ZodType<AnnotationTaskCreate> = z
  .object({
    description: z.string().nullable().optional().describe(
      "A description for the task. Omit for none",
    ),
    evaluator_ids: z.array(z.string()).nullable().optional().describe(
      "IDs of evaluators to link when the task is created, in order. Each must be one you created or a built-in default. Omit to create with no linked evaluators",
    ),
    name: z.string().describe("Task name, unique within your workspace"),
    type: AnnotationTaskCreateType$zodSchema.describe(
      "Task type. Determines the shape of each item's payload.\n- `stt`: judge a transcript on its own\n- `llm`: judge one response with its conversation history\n- `llm-general`: judge a standalone `input -> output` pair\n- `conversation`: judge a full conversation",
    ),
  });
