/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotatorResponse = {
  uuid: string;
  name: string;
  created_at: string;
  updated_at: string;
  jobs_count?: number | null | undefined;
  current_agreement?: number | null | undefined;
  pair_count?: number | null | undefined;
};

export const AnnotatorResponse$zodSchema: z.ZodType<AnnotatorResponse> = z
  .object({
    created_at: z.string().describe(
      "When the annotator was created (ISO 8601 UTC)",
    ),
    current_agreement: z.number().nullable().optional().describe(
      "Latest pairwise mean agreement with other annotators, from 0 to 1",
    ),
    jobs_count: z.int().nullable().optional().describe(
      "Number of labelling jobs assigned to this annotator",
    ),
    name: z.string().describe("Annotator name"),
    pair_count: z.int().nullable().optional().describe(
      "Number of comparable annotation pairs behind the current agreement score",
    ),
    updated_at: z.string().describe(
      "When the annotator was last updated (ISO 8601 UTC)",
    ),
    uuid: z.string().describe("Annotator ID"),
  });
