/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotatorUpdate = { name?: string | null | undefined };

export const AnnotatorUpdate$zodSchema: z.ZodType<AnnotatorUpdate> = z.object({
  name: z.string().nullable().optional().describe(
    "New annotator name, unique within your workspace. Omit to leave unchanged",
  ),
});
