/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Task type. Determines the shape of each item's payload.
 *
 * @remarks
 * - `stt`: judge a transcript on its own
 * - `llm`: judge one response with its conversation history
 * - `llm-general`: judge a standalone `input -> output` pair
 * - `conversation`: judge a full conversation
 */
export const AnnotationTaskResponseType = {
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
} as const;
/**
 * Task type. Determines the shape of each item's payload.
 *
 * @remarks
 * - `stt`: judge a transcript on its own
 * - `llm`: judge one response with its conversation history
 * - `llm-general`: judge a standalone `input -> output` pair
 * - `conversation`: judge a full conversation
 */
export type AnnotationTaskResponseType = ClosedEnum<
  typeof AnnotationTaskResponseType
>;

export const AnnotationTaskResponseType$zodSchema = z.enum([
  "stt",
  "llm",
  "llm-general",
  "conversation",
]).describe(
  "Task type. Determines the shape of each item's payload.\n- `stt`: judge a transcript on its own\n- `llm`: judge one response with its conversation history\n- `llm-general`: judge a standalone `input -> output` pair\n- `conversation`: judge a full conversation",
);

export type AnnotationTaskResponse = {
  uuid: string;
  name: string;
  type: AnnotationTaskResponseType;
  description?: string | null | undefined;
  created_at: string;
  updated_at: string;
  evaluators?: Array<{ [k: string]: any }> | undefined;
  item_count?: number | null | undefined;
  items?: Array<{ [k: string]: any }> | undefined;
  jobs?: Array<{ [k: string]: any }> | undefined;
};

export const AnnotationTaskResponse$zodSchema: z.ZodType<
  AnnotationTaskResponse
> = z.object({
  created_at: z.string().describe("When the task was created (ISO 8601 UTC)"),
  description: z.string().nullable().optional().describe(
    "The task's description",
  ),
  evaluators: z.array(z.record(z.string(), z.any())).optional().describe(
    "The evaluators linked to this task, in display order, each with its live version's rubric",
  ),
  item_count: z.int().nullable().optional().describe(
    "Number of items in the task",
  ),
  items: z.array(z.record(z.string(), z.any())).optional().describe(
    "The task's items, each with its agreement stats. You get these when you fetch one task by ID, not when you list tasks",
  ),
  jobs: z.array(z.record(z.string(), z.any())).optional().describe(
    "The task's labelling jobs. You get these when you fetch one task by ID, not when you list tasks",
  ),
  name: z.string().describe("Name of the task"),
  type: AnnotationTaskResponseType$zodSchema.describe(
    "Task type. Determines the shape of each item's payload.\n- `stt`: judge a transcript on its own\n- `llm`: judge one response with its conversation history\n- `llm-general`: judge a standalone `input -> output` pair\n- `conversation`: judge a full conversation",
  ),
  updated_at: z.string().describe(
    "When the task was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("Unique ID for the task"),
});
