/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotationTaskCreateResponse = { uuid: string; message: string };

export const AnnotationTaskCreateResponse$zodSchema: z.ZodType<
  AnnotationTaskCreateResponse
> = z.object({
  message: z.string().describe("Confirmation that the task was created"),
  uuid: z.string().describe("ID of the newly created task"),
});
