/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotationItemPayload = {
  payload?: any | undefined;
  annotations?: { [k: string]: any } | null | undefined;
};

export const AnnotationItemPayload$zodSchema: z.ZodType<AnnotationItemPayload> =
  z.object({
    annotations: z.record(z.string(), z.any()).nullable().optional().describe(
      "Human annotations to seed, keyed by evaluator ID. Each evaluator ID must be linked to the task. Put the judgement in `value`, a bool for binary or a number for rating, with optional `reasoning`. Requires `annotator_id`",
    ),
    payload: z.any().optional().describe(
      "The item's payload. Its shape depends on the task `type`. `payload['name']` is **required** for every type and must be unique within the task",
    ),
  });
