/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AnnotatorCreate = { name: string };

export const AnnotatorCreate$zodSchema: z.ZodType<AnnotatorCreate> = z.object({
  name: z.string().describe("Annotator name, unique within your workspace"),
});
