/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BatchRunRequest = {
  agent_names?: Array<string> | null | undefined;
};

export const BatchRunRequest$zodSchema: z.ZodType<BatchRunRequest> = z.object({
  agent_names: z.array(z.string()).nullable().optional().describe(
    "Agents to run. Omit to run every agent in your workspace",
  ),
});
