/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BatchTestRun, BatchTestRun$zodSchema } from "./batchtestrun.js";
import { BatchTestSkip, BatchTestSkip$zodSchema } from "./batchtestskip.js";

export type BatchTestRunResponse = {
  runs: Array<BatchTestRun>;
  skipped?: Array<BatchTestSkip> | undefined;
};

export const BatchTestRunResponse$zodSchema: z.ZodType<BatchTestRunResponse> = z
  .object({
    runs: z.array(BatchTestRun$zodSchema).describe(
      "Test runs that were launched",
    ),
    skipped: z.array(BatchTestSkip$zodSchema).optional().describe(
      "Agents that were skipped instead of failing the batch",
    ),
  });
