/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Initial status of the test run
 */
export const BatchTestRunStatus = {
  Queued: "queued",
  InProgress: "in_progress",
} as const;
/**
 * Initial status of the test run
 */
export type BatchTestRunStatus = ClosedEnum<typeof BatchTestRunStatus>;

export const BatchTestRunStatus$zodSchema = z.enum([
  "queued",
  "in_progress",
]).describe("Initial status of the test run");

export type BatchTestRun = {
  agent_name: string;
  agent_uuid: string;
  task_id: string;
  status: BatchTestRunStatus;
};

export const BatchTestRun$zodSchema: z.ZodType<BatchTestRun> = z.object({
  agent_name: z.string().describe("Name of the agent"),
  agent_uuid: z.string().describe("ID of the agent that was run"),
  status: BatchTestRunStatus$zodSchema.describe(
    "Initial status of the test run",
  ),
  task_id: z.string().describe("Test run job ID. Poll for status and results"),
});
