/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BatchTestSkip = {
  agent_name: string;
  agent_uuid: string;
  reason: string;
};

export const BatchTestSkip$zodSchema: z.ZodType<BatchTestSkip> = z.object({
  agent_name: z.string().describe("Name of the skipped agent"),
  agent_uuid: z.string().describe("ID of the skipped agent"),
  reason: z.string().describe("Why this agent was not run"),
});
