/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BulkCreateItemsResponse,
  BulkCreateItemsResponse$zodSchema,
} from "./bulkcreateitemsresponse.js";
import {
  BulkItemsRequest,
  BulkItemsRequest$zodSchema,
} from "./bulkitemsrequest.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type BulkCreateItemsAnnotationTasksTaskUuidItemsPostRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: BulkItemsRequest;
};

export const BulkCreateItemsAnnotationTasksTaskUuidItemsPostRequest$zodSchema:
  z.ZodType<BulkCreateItemsAnnotationTasksTaskUuidItemsPostRequest> = z.object({
    body: BulkItemsRequest$zodSchema,
    task_uuid: z.string().describe("Annotation task to act on"),
    xAPIKey: z.string().nullable().optional(),
  });

export type BulkCreateItemsAnnotationTasksTaskUuidItemsPostResponse =
  | BulkCreateItemsResponse
  | HTTPValidationError;

export const BulkCreateItemsAnnotationTasksTaskUuidItemsPostResponse$zodSchema:
  z.ZodType<BulkCreateItemsAnnotationTasksTaskUuidItemsPostResponse> = z.union([
    BulkCreateItemsResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
