/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotationItemPayload,
  AnnotationItemPayload$zodSchema,
} from "./annotationitempayload.js";

export type BulkItemsRequest = {
  items: Array<AnnotationItemPayload>;
  annotator_id?: string | null | undefined;
};

export const BulkItemsRequest$zodSchema: z.ZodType<BulkItemsRequest> = z.object(
  {
    annotator_id: z.string().nullable().optional().describe(
      "Annotator these initial annotations belong to. Required when any item carries annotations",
    ),
    items: z.array(AnnotationItemPayload$zodSchema).describe(
      "Items to insert. Insertion order is preserved",
    ),
  },
);
