/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestBulkDelete,
  AgentTestBulkDelete$zodSchema,
} from "./agenttestbulkdelete.js";
import {
  AgentTestsBulkUnlinkResponse,
  AgentTestsBulkUnlinkResponse$zodSchema,
} from "./agenttestsbulkunlinkresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest = {
  xAPIKey?: string | null | undefined;
  body: AgentTestBulkDelete;
};

export const BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest$zodSchema:
  z.ZodType<BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostRequest> = z.object(
    {
      body: AgentTestBulkDelete$zodSchema,
      xAPIKey: z.string().nullable().optional(),
    },
  );

export type BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse =
  | AgentTestsBulkUnlinkResponse
  | HTTPValidationError;

export const BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse$zodSchema:
  z.ZodType<BulkDeleteAgentTestLinksAgentTestsBulkUnlinkPostResponse> = z.union(
    [
      AgentTestsBulkUnlinkResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ],
  );
