/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BulkUpdateItemsResponse = { updated_count: number };

export const BulkUpdateItemsResponse$zodSchema: z.ZodType<
  BulkUpdateItemsResponse
> = z.object({
  updated_count: z.int().describe("How many items were updated"),
});
