/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChatMessage, ChatMessage$zodSchema } from "./chatmessage.js";
import {
  ExpectedToolCall,
  ExpectedToolCall$zodSchema,
} from "./expectedtoolcall.js";
import {
  RoutersTestsEvaluatorRef,
  RoutersTestsEvaluatorRef$zodSchema,
} from "./routerstestsevaluatorref.js";

export type BulkTestItem = {
  name: string;
  conversation_history?: Array<ChatMessage> | null | undefined;
  input?: string | null | undefined;
  evaluators?: Array<RoutersTestsEvaluatorRef> | null | undefined;
  tool_calls?: Array<ExpectedToolCall> | null | undefined;
  inputs?: { [k: string]: any } | null | undefined;
};

export const BulkTestItem$zodSchema: z.ZodType<BulkTestItem> = z.object({
  conversation_history: z.array(ChatMessage$zodSchema).nullable().optional()
    .describe(
      "Ordered messages ending at the user turn the agent should answer. **Required for `response` and `conversation` batches**, and for `tool_call` batches aimed at a conversational agent",
    ),
  evaluators: z.array(RoutersTestsEvaluatorRef$zodSchema).nullable().optional()
    .describe(
      "Evaluators to link. Used by `response`, `conversation`, and `general` tests",
    ),
  input: z.string().nullable().optional().describe(
    "Standalone prompt with no conversation around it. **Required for `general` batches**, and for `tool_call` batches aimed at a general agent",
  ),
  inputs: z.record(z.string(), z.any()).nullable().optional().describe(
    "Extra request fields for this test, overriding the agent's `default_inputs` per key",
  ),
  name: z.string().describe(
    "Name of the test, unique within the workspace and within the batch",
  ),
  tool_calls: z.array(ExpectedToolCall$zodSchema).nullable().optional()
    .describe("Expected tool calls. **Required for `tool_call` batches**"),
});
