/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChatMessage, ChatMessage$zodSchema } from "./chatmessage.js";
import {
  ExpectedToolCall,
  ExpectedToolCall$zodSchema,
} from "./expectedtoolcall.js";
import {
  RoutersTestsEvaluatorRef,
  RoutersTestsEvaluatorRef$zodSchema,
} from "./routerstestsevaluatorref.js";

export type BulkTestItem = {
  name: string;
  conversation_history: Array<ChatMessage>;
  evaluators?: Array<RoutersTestsEvaluatorRef> | null | undefined;
  tool_calls?: Array<ExpectedToolCall> | null | undefined;
};

export const BulkTestItem$zodSchema: z.ZodType<BulkTestItem> = z.object({
  conversation_history: z.array(ChatMessage$zodSchema).describe(
    "Ordered messages ending at the user turn the agent should answer",
  ),
  evaluators: z.array(RoutersTestsEvaluatorRef$zodSchema).nullable().optional()
    .describe(
      "Evaluators to link. Used by `response` and `conversation` tests",
    ),
  name: z.string().describe(
    "Name of the test, unique within the workspace and within the batch",
  ),
  tool_calls: z.array(ExpectedToolCall$zodSchema).nullable().optional()
    .describe("Expected tool calls. **Required for `tool_call` batches**"),
});
