/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BulkUpdateItemsRequest,
  BulkUpdateItemsRequest$zodSchema,
} from "./bulkupdateitemsrequest.js";
import {
  BulkUpdateItemsResponse,
  BulkUpdateItemsResponse$zodSchema,
} from "./bulkupdateitemsresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type BulkUpdateItemsAnnotationTasksTaskUuidItemsPutRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: BulkUpdateItemsRequest;
};

export const BulkUpdateItemsAnnotationTasksTaskUuidItemsPutRequest$zodSchema:
  z.ZodType<BulkUpdateItemsAnnotationTasksTaskUuidItemsPutRequest> = z.object({
    body: BulkUpdateItemsRequest$zodSchema,
    task_uuid: z.string().describe("Annotation task to act on"),
    xAPIKey: z.string().nullable().optional(),
  });

export type BulkUpdateItemsAnnotationTasksTaskUuidItemsPutResponse =
  | BulkUpdateItemsResponse
  | HTTPValidationError;

export const BulkUpdateItemsAnnotationTasksTaskUuidItemsPutResponse$zodSchema:
  z.ZodType<BulkUpdateItemsAnnotationTasksTaskUuidItemsPutResponse> = z.union([
    BulkUpdateItemsResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
