/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BulkTestUpload, BulkTestUpload$zodSchema } from "./bulktestupload.js";
import {
  BulkTestUploadResponse,
  BulkTestUploadResponse$zodSchema,
} from "./bulktestuploadresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type BulkUploadTestsTestsBulkPostRequest = {
  xAPIKey?: string | null | undefined;
  body: BulkTestUpload;
};

export const BulkUploadTestsTestsBulkPostRequest$zodSchema: z.ZodType<
  BulkUploadTestsTestsBulkPostRequest
> = z.object({
  body: BulkTestUpload$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type BulkUploadTestsTestsBulkPostResponse =
  | BulkTestUploadResponse
  | HTTPValidationError;

export const BulkUploadTestsTestsBulkPostResponse$zodSchema: z.ZodType<
  BulkUploadTestsTestsBulkPostResponse
> = z.union([
  BulkTestUploadResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
