/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BulkTestUploadResponse = {
  uuids: Array<string>;
  count: number;
  message: string;
  warnings?: Array<string> | null | undefined;
};

export const BulkTestUploadResponse$zodSchema: z.ZodType<
  BulkTestUploadResponse
> = z.object({
  count: z.int().describe("Number of tests created"),
  message: z.string().describe("Confirmation message"),
  uuids: z.array(z.string()).describe(
    "IDs of the created tests, in request order",
  ),
  warnings: z.array(z.string()).nullable().optional().describe(
    "Non-fatal issues (e.g. agents some tests couldn't link to). Null when there were none",
  ),
});
