/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ItemUpdatePayload,
  ItemUpdatePayload$zodSchema,
} from "./itemupdatepayload.js";

export type BulkUpdateItemsRequest = { updates: Array<ItemUpdatePayload> };

export const BulkUpdateItemsRequest$zodSchema: z.ZodType<
  BulkUpdateItemsRequest
> = z.object({
  updates: z.array(ItemUpdatePayload$zodSchema).describe(
    "The new payload for each item you're updating. Entries not in this task, or referencing deleted items, are skipped",
  ),
});
