/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BulkTestItem, BulkTestItem$zodSchema } from "./bulktestitem.js";

/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 *
 * Applied to every test in the batch.
 */
export const BulkTestUploadType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 *
 * Applied to every test in the batch.
 */
export type BulkTestUploadType = ClosedEnum<typeof BulkTestUploadType>;

export const BulkTestUploadType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]).describe(
  "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n\nApplied to every test in the batch.",
);

export type BulkTestUpload = {
  type: BulkTestUploadType;
  tests: Array<BulkTestItem>;
  agent_uuids?: Array<string> | null | undefined;
  language?: string | null | undefined;
};

export const BulkTestUpload$zodSchema: z.ZodType<BulkTestUpload> = z.object({
  agent_uuids: z.array(z.string()).nullable().optional().describe(
    "Agents (IDs) to link every created test to. Omit to link none",
  ),
  language: z.string().nullable().optional().describe(
    "Language written to each test's `config.settings.language`. Omit to leave unset",
  ),
  tests: z.array(BulkTestItem$zodSchema).describe(
    "Test items to create (non-empty, max 500 per request, names unique within the batch)",
  ),
  type: BulkTestUploadType$zodSchema.describe(
    "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n\nApplied to every test in the batch.",
  ),
});
