/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BulkCreateItemsResponse = {
  item_ids: Array<string>;
  count: number;
  new_item_ids?: Array<string> | null | undefined;
  existing_item_ids?: Array<string> | null | undefined;
  annotation_job_id?: string | null | undefined;
  evaluator_result_count?: number | null | undefined;
  evaluator_run_job_id?: string | null | undefined;
};

export const BulkCreateItemsResponse$zodSchema: z.ZodType<
  BulkCreateItemsResponse
> = z.object({
  annotation_job_id: z.string().nullable().optional().describe(
    "ID of the labelling job that holds the annotations you provided, present only when you send annotations with the items",
  ),
  count: z.int().describe("How many items the request resolved to"),
  evaluator_result_count: z.int().nullable().optional().describe(
    "How many evaluator scores were stored, present only when you send `evaluator_results` with the items",
  ),
  evaluator_run_job_id: z.string().nullable().optional().describe(
    "ID of the evaluator-run job that holds the scores you provided, present only when you send `evaluator_results` with the items",
  ),
  existing_item_ids: z.array(z.string()).nullable().optional().describe(
    "IDs of items that already existed by name and were reused",
  ),
  item_ids: z.array(z.string()).describe(
    "IDs of every item the request resolved to, in request order",
  ),
  new_item_ids: z.array(z.string()).nullable().optional().describe(
    "IDs of the items that were newly created",
  ),
});
