/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Message author role in the conversation history
 */
export const Role = {
  User: "user",
  Assistant: "assistant",
  Tool: "tool",
} as const;
/**
 * Message author role in the conversation history
 */
export type Role = ClosedEnum<typeof Role>;

export const Role$zodSchema = z.enum([
  "user",
  "assistant",
  "tool",
]).describe("Message author role in the conversation history");

export type ChatMessage = {
  role: Role;
  content?: string | null | undefined;
  tool_calls?: Array<{ [k: string]: any }> | null | undefined;
  tool_call_id?: string | null | undefined;
  name?: string | null | undefined;
};

export const ChatMessage$zodSchema: z.ZodType<ChatMessage> = z.object({
  content: z.string().nullable().optional().describe(
    "Message text. Omit for assistant messages that only carry `tool_calls`",
  ),
  name: z.string().nullable().optional().describe(
    "Tool name for `role=tool` messages. Omit otherwise",
  ),
  role: Role$zodSchema.describe(
    "Message author role in the conversation history",
  ),
  tool_call_id: z.string().nullable().optional().describe(
    "ID of the tool call this message responds to. **Required for `role=tool`**",
  ),
  tool_calls: z.array(z.record(z.string(), z.any())).nullable().optional()
    .describe("Tool calls issued by the assistant. Omit for plain text turns"),
});
