/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateJobsRequest = {
  annotator_ids: Array<string>;
  item_ids?: Array<string> | undefined;
  select_all?: boolean | undefined;
  q?: string | null | undefined;
  evaluator_ids?: Array<string> | null | undefined;
};

export const CreateJobsRequest$zodSchema: z.ZodType<CreateJobsRequest> = z
  .object({
    annotator_ids: z.array(z.string()).describe(
      "Annotator IDs to assign, creating one labelling job for each annotator. Must be in your workspace",
    ),
    evaluator_ids: z.array(z.string()).nullable().optional().describe(
      "Subset of the task's linked evaluators to show in these jobs. Must be a subset of the current links, an empty list gives a 400. Applies to every annotator's job. Omit (`None`) to snapshot every linked evaluator",
    ),
    item_ids: z.array(z.string()).optional().describe(
      "Item IDs to assign. **Required when `select_all=false`**. Ignored when `select_all=true`",
    ),
    q: z.string().nullable().optional().describe(
      "Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`",
    ),
    select_all: z.boolean().default(false).describe(
      "When `true`, assign every item in the task and ignore `item_ids`. Set `q` to assign only items whose name matches it",
    ),
  });
