/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateJobsRequest,
  CreateJobsRequest$zodSchema,
} from "./createjobsrequest.js";
import {
  CreateJobsResponse,
  CreateJobsResponse$zodSchema,
} from "./createjobsresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateJobsAnnotationTasksTaskUuidJobsPostRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: CreateJobsRequest;
};

export const CreateJobsAnnotationTasksTaskUuidJobsPostRequest$zodSchema:
  z.ZodType<CreateJobsAnnotationTasksTaskUuidJobsPostRequest> = z.object({
    body: CreateJobsRequest$zodSchema,
    task_uuid: z.string().describe("Annotation task to act on"),
    xAPIKey: z.string().nullable().optional(),
  });

export type CreateJobsAnnotationTasksTaskUuidJobsPostResponse =
  | CreateJobsResponse
  | HTTPValidationError;

export const CreateJobsAnnotationTasksTaskUuidJobsPostResponse$zodSchema:
  z.ZodType<CreateJobsAnnotationTasksTaskUuidJobsPostResponse> = z.union([
    CreateJobsResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
