/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LabellingJobCreated,
  LabellingJobCreated$zodSchema,
} from "./labellingjobcreated.js";

export type CreateJobsResponse = {
  jobs: Array<LabellingJobCreated>;
  count: number;
};

export const CreateJobsResponse$zodSchema: z.ZodType<CreateJobsResponse> = z
  .object({
    count: z.int().describe("How many jobs were created"),
    jobs: z.array(LabellingJobCreated$zodSchema).describe(
      "The jobs created, one for each annotator",
    ),
  });
