/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorVersionCreateRequest,
  EvaluatorVersionCreateRequest$zodSchema,
} from "./evaluatorversioncreaterequest.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  VersionCreateResponse,
  VersionCreateResponse$zodSchema,
} from "./versioncreateresponse.js";

export type CreateVersionEvaluatorsEvaluatorUuidVersionsPostRequest = {
  evaluator_uuid: string;
  xAPIKey?: string | null | undefined;
  body: EvaluatorVersionCreateRequest;
};

export const CreateVersionEvaluatorsEvaluatorUuidVersionsPostRequest$zodSchema:
  z.ZodType<CreateVersionEvaluatorsEvaluatorUuidVersionsPostRequest> = z.object(
    {
      body: EvaluatorVersionCreateRequest$zodSchema,
      evaluator_uuid: z.string().describe("Evaluator to add a version to"),
      xAPIKey: z.string().nullable().optional(),
    },
  );

export type CreateVersionEvaluatorsEvaluatorUuidVersionsPostResponse =
  | VersionCreateResponse
  | HTTPValidationError;

export const CreateVersionEvaluatorsEvaluatorUuidVersionsPostResponse$zodSchema:
  z.ZodType<CreateVersionEvaluatorsEvaluatorUuidVersionsPostResponse> = z.union(
    [
      VersionCreateResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ],
  );
