/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentCreate, AgentCreate$zodSchema } from "./agentcreate.js";
import {
  AgentCreateResponse,
  AgentCreateResponse$zodSchema,
} from "./agentcreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateAgentEndpointAgentsPostRequest = {
  xAPIKey?: string | null | undefined;
  body: AgentCreate;
};

export const CreateAgentEndpointAgentsPostRequest$zodSchema: z.ZodType<
  CreateAgentEndpointAgentsPostRequest
> = z.object({
  body: AgentCreate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type CreateAgentEndpointAgentsPostResponse =
  | AgentCreateResponse
  | HTTPValidationError;

export const CreateAgentEndpointAgentsPostResponse$zodSchema: z.ZodType<
  CreateAgentEndpointAgentsPostResponse
> = z.union([
  AgentCreateResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
