/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestsCreate,
  AgentTestsCreate$zodSchema,
} from "./agenttestscreate.js";
import {
  AgentTestsCreateResponse,
  AgentTestsCreateResponse$zodSchema,
} from "./agenttestscreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateAgentTestLinksAgentTestsPostRequest = {
  xAPIKey?: string | null | undefined;
  body: AgentTestsCreate;
};

export const CreateAgentTestLinksAgentTestsPostRequest$zodSchema: z.ZodType<
  CreateAgentTestLinksAgentTestsPostRequest
> = z.object({
  body: AgentTestsCreate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type CreateAgentTestLinksAgentTestsPostResponse =
  | AgentTestsCreateResponse
  | HTTPValidationError;

export const CreateAgentTestLinksAgentTestsPostResponse$zodSchema: z.ZodType<
  CreateAgentTestLinksAgentTestsPostResponse
> = z.union([
  AgentTestsCreateResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
