/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorCreate,
  EvaluatorCreate$zodSchema,
} from "./evaluatorcreate.js";
import {
  EvaluatorCreateResponse,
  EvaluatorCreateResponse$zodSchema,
} from "./evaluatorcreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateEvaluatorEndpointEvaluatorsPostRequest = {
  xAPIKey?: string | null | undefined;
  body: EvaluatorCreate;
};

export const CreateEvaluatorEndpointEvaluatorsPostRequest$zodSchema: z.ZodType<
  CreateEvaluatorEndpointEvaluatorsPostRequest
> = z.object({
  body: EvaluatorCreate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type CreateEvaluatorEndpointEvaluatorsPostResponse =
  | EvaluatorCreateResponse
  | HTTPValidationError;

export const CreateEvaluatorEndpointEvaluatorsPostResponse$zodSchema: z.ZodType<
  CreateEvaluatorEndpointEvaluatorsPostResponse
> = z.union([
  EvaluatorCreateResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
