/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotatorCreate,
  AnnotatorCreate$zodSchema,
} from "./annotatorcreate.js";
import {
  AnnotatorCreateResponse,
  AnnotatorCreateResponse$zodSchema,
} from "./annotatorcreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateAnnotatorEndpointAnnotatorsPostRequest = {
  xAPIKey?: string | null | undefined;
  body: AnnotatorCreate;
};

export const CreateAnnotatorEndpointAnnotatorsPostRequest$zodSchema: z.ZodType<
  CreateAnnotatorEndpointAnnotatorsPostRequest
> = z.object({
  body: AnnotatorCreate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type CreateAnnotatorEndpointAnnotatorsPostResponse =
  | AnnotatorCreateResponse
  | HTTPValidationError;

export const CreateAnnotatorEndpointAnnotatorsPostResponse$zodSchema: z.ZodType<
  CreateAnnotatorEndpointAnnotatorsPostResponse
> = z.union([
  AnnotatorCreateResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
