/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { TestCreate, TestCreate$zodSchema } from "./testcreate.js";
import {
  TestCreateResponse,
  TestCreateResponse$zodSchema,
} from "./testcreateresponse.js";

export type CreateTestEndpointTestsPostRequest = {
  xAPIKey?: string | null | undefined;
  xOrgUUID?: string | null | undefined;
  body: TestCreate;
};

export const CreateTestEndpointTestsPostRequest$zodSchema: z.ZodType<
  CreateTestEndpointTestsPostRequest
> = z.object({
  body: TestCreate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
  xOrgUUID: z.string().nullable().optional(),
});

export type CreateTestEndpointTestsPostResponse =
  | TestCreateResponse
  | HTTPValidationError;

export const CreateTestEndpointTestsPostResponse$zodSchema: z.ZodType<
  CreateTestEndpointTestsPostResponse
> = z.union([
  TestCreateResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
