/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotationTaskCreate,
  AnnotationTaskCreate$zodSchema,
} from "./annotationtaskcreate.js";
import {
  AnnotationTaskCreateResponse,
  AnnotationTaskCreateResponse$zodSchema,
} from "./annotationtaskcreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type CreateAnnotationTaskEndpointAnnotationTasksPostRequest = {
  xAPIKey?: string | null | undefined;
  body: AnnotationTaskCreate;
};

export const CreateAnnotationTaskEndpointAnnotationTasksPostRequest$zodSchema:
  z.ZodType<CreateAnnotationTaskEndpointAnnotationTasksPostRequest> = z.object({
    body: AnnotationTaskCreate$zodSchema,
    xAPIKey: z.string().nullable().optional(),
  });

export type CreateAnnotationTaskEndpointAnnotationTasksPostResponse =
  | AnnotationTaskCreateResponse
  | HTTPValidationError;

export const CreateAnnotationTaskEndpointAnnotationTasksPostResponse$zodSchema:
  z.ZodType<CreateAnnotationTaskEndpointAnnotationTasksPostResponse> = z.union([
    AnnotationTaskCreateResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
