/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { OutputConfig, OutputConfig$zodSchema } from "./outputconfig.js";
import { VariableSpec, VariableSpec$zodSchema } from "./variablespec.js";

/**
 * Request body for adding a version to an existing evaluator.
 */
export type EvaluatorVersionCreateRequest = {
  judge_model: string;
  system_prompt: string;
  output_config?: OutputConfig | null | undefined;
  variables?: Array<VariableSpec> | null | undefined;
  make_live?: boolean | undefined;
};

export const EvaluatorVersionCreateRequest$zodSchema: z.ZodType<
  EvaluatorVersionCreateRequest
> = z.object({
  judge_model: z.string().describe(
    "The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`",
  ),
  make_live: z.boolean().default(false).describe(
    "When `true`, immediately point the evaluator's live version at this new version",
  ),
  output_config: OutputConfig$zodSchema.nullable().optional().describe(
    "The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own",
  ),
  system_prompt: z.string().describe(
    "Judge system prompt. May contain `{{\"{{\"}}variable}}` placeholders",
  ),
  variables: z.array(VariableSpec$zodSchema).nullable().optional().describe(
    "Declared prompt variables. Omit if the prompt has none. After the first version the variable names are fixed. You can change a variable's description or default, but not add, remove, or rename one",
  ),
}).describe("Request body for adding a version to an existing evaluator.");
