/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { OutputConfig, OutputConfig$zodSchema } from "./outputconfig.js";
import { VariableSpec, VariableSpec$zodSchema } from "./variablespec.js";

export type EvaluatorVersionCompact = {
  uuid: string;
  version_number: number;
  judge_model: string;
  system_prompt?: string | null | undefined;
  output_config?: OutputConfig | null | undefined;
  variables?: Array<VariableSpec> | null | undefined;
  created_at: string;
};

export const EvaluatorVersionCompact$zodSchema: z.ZodType<
  EvaluatorVersionCompact
> = z.object({
  created_at: z.string().describe(
    "When the version was created (ISO 8601 UTC)",
  ),
  judge_model: z.string().describe(
    "The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`",
  ),
  output_config: OutputConfig$zodSchema.nullable().optional().describe(
    "The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own",
  ),
  system_prompt: z.string().nullable().optional().describe(
    "Judge system prompt, with `{{\"{{\"}}variable}}` placeholders unrendered",
  ),
  uuid: z.string().describe("Version ID"),
  variables: z.array(VariableSpec$zodSchema).nullable().optional().describe(
    "Declared prompt variables",
  ),
  version_number: z.int().describe(
    "The version's number. The first version is 1, and it goes up by one for each new version of the evaluator",
  ),
});
