/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorLinkRequest = { evaluator_ids: Array<string> };

export const EvaluatorLinkRequest$zodSchema: z.ZodType<EvaluatorLinkRequest> = z
  .object({
    evaluator_ids: z.array(z.string()).describe(
      "The evaluators to link to the agent. Ones that are already linked are skipped. Each must be one you created or a built-in default",
    ),
  });
