/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorLinkResponse = { message: string };

export const EvaluatorLinkResponse$zodSchema: z.ZodType<EvaluatorLinkResponse> =
  z.object({
    message: z.string().describe("Confirmation that the evaluator was linked"),
  });
