/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorSetResponse = {
  message: string;
  evaluator_ids: Array<string>;
  linked: Array<string>;
  unlinked: Array<string>;
};

export const EvaluatorSetResponse$zodSchema: z.ZodType<EvaluatorSetResponse> = z
  .object({
    evaluator_ids: z.array(z.string()).describe(
      "The task's evaluator IDs after the update, in display order",
    ),
    linked: z.array(z.string()).describe(
      "Evaluator IDs newly linked by this request",
    ),
    message: z.string().describe(
      "Confirmation that the task's evaluators were updated",
    ),
    unlinked: z.array(z.string()).describe(
      "Evaluator IDs unlinked by this request",
    ),
  });
