/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Current status of the job
 */
export const EvaluatorRunResponseStatus = {
  Queued: "queued",
  InProgress: "in_progress",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Current status of the job
 */
export type EvaluatorRunResponseStatus = ClosedEnum<
  typeof EvaluatorRunResponseStatus
>;

export const EvaluatorRunResponseStatus$zodSchema = z.enum([
  "queued",
  "in_progress",
  "completed",
  "failed",
]).describe("Current status of the job");

export type EvaluatorRunResponse = {
  uuid: string;
  task_id: string | null;
  status: EvaluatorRunResponseStatus;
  error: string | null;
  completed_at: string | null;
  evaluators: Array<{ [k: string]: any }>;
  runs: Array<{ [k: string]: any }>;
  human_agreement: { [k: string]: any };
  items: Array<{ [k: string]: any }>;
  is_public: boolean;
  share_token: string | null;
  AdditionalProperties?: { [k: string]: any };
};

export const EvaluatorRunResponse$zodSchema: z.ZodType<EvaluatorRunResponse> =
  collectExtraKeys$(
    z.object({
      completed_at: z.string().nullable().describe(
        "When the job finished (ISO 8601 UTC)",
      ),
      error: z.string().nullable().describe(
        "Failure reason, present when the job failed",
      ),
      evaluators: z.array(z.record(z.string(), z.any())).describe(
        "The evaluators the job ran, each pinned to the version it used, with that version's rubric",
      ),
      human_agreement: z.record(z.string(), z.any()).describe(
        "How each evaluator's judgements line up with the human annotations on the same items",
      ),
      is_public: z.boolean().describe("Whether the run is shared publicly"),
      items: z.array(z.record(z.string(), z.any())).describe(
        "The exact item set the job ran on, frozen when the job started",
      ),
      runs: z.array(z.record(z.string(), z.any())).describe(
        "One result per item and evaluator. Each keys back to `evaluators` by its evaluator and version IDs",
      ),
      share_token: z.string().nullable().describe(
        "Token for building the public share URL",
      ),
      status: EvaluatorRunResponseStatus$zodSchema.describe(
        "Current status of the job",
      ),
      task_id: z.string().nullable().describe("ID of the task the job ran on"),
      uuid: z.string().describe("ID of the evaluator-run job"),
    }).catchall(z.any()),
    "AdditionalProperties",
    true,
  );

export const EvaluatorRunResponse$zodSchemaOutbound: z.ZodType<any> = z.object({
  AdditionalProperties: z.record(z.string(), z.any()).optional(),
  completed_at: z.nullable(z.string()),
  error: z.nullable(z.string()),
  evaluators: z.array(z.record(z.string(), z.any())),
  human_agreement: z.record(z.string(), z.any()),
  is_public: z.boolean(),
  items: z.array(z.record(z.string(), z.any())),
  runs: z.array(z.record(z.string(), z.any())),
  share_token: z.nullable(z.string()),
  status: EvaluatorRunResponseStatus$zodSchema,
  task_id: z.nullable(z.string()),
  uuid: z.string(),
}).transform((v) => {
  const { AdditionalProperties, ...rest } = v;
  return {
    ...rest,
    ...AdditionalProperties,
  };
});
