/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorLinkRequest = { evaluator_id: string };

export const EvaluatorLinkRequest$zodSchema: z.ZodType<EvaluatorLinkRequest> = z
  .object({
    evaluator_id: z.string().describe(
      "The evaluator to link. Must be one you created or a built-in default",
    ),
  });
