/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorCreateResponse = { uuid: string; version_uuid: string };

export const EvaluatorCreateResponse$zodSchema: z.ZodType<
  EvaluatorCreateResponse
> = z.object({
  uuid: z.string().describe("ID of the created evaluator"),
  version_uuid: z.string().describe("ID of its initial version"),
});
