/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorRunRequestEntry,
  EvaluatorRunRequestEntry$zodSchema,
} from "./evaluatorrunrequestentry.js";

export type EvaluatorRunStartRequest = {
  evaluators: Array<EvaluatorRunRequestEntry>;
  item_ids?: Array<string> | undefined;
  select_all?: boolean | undefined;
  q?: string | null | undefined;
};

export const EvaluatorRunStartRequest$zodSchema: z.ZodType<
  EvaluatorRunStartRequest
> = z.object({
  evaluators: z.array(EvaluatorRunRequestEntry$zodSchema).describe(
    "The evaluators to run. Each must be linked to the task",
  ),
  item_ids: z.array(z.string()).optional().describe(
    "Item IDs to run on. **Required when `select_all=false`**. Ignored when `select_all=true`",
  ),
  q: z.string().nullable().optional().describe(
    "Case-insensitive substring filter on `payload.name`. Applies only when `select_all=true`",
  ),
  select_all: z.boolean().default(false).describe(
    "When `true`, run on every item in the task. Set `q` to run only items whose name matches it",
  ),
});
