/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorRunRequestEntry = {
  evaluator_id: string;
  evaluator_version_id?: string | null | undefined;
};

export const EvaluatorRunRequestEntry$zodSchema: z.ZodType<
  EvaluatorRunRequestEntry
> = z.object({
  evaluator_id: z.string().describe(
    "Evaluator ID to run. Must be linked to the task",
  ),
  evaluator_version_id: z.string().nullable().optional().describe(
    "Evaluator version ID to run. Omit to use the evaluator's live version",
  ),
});
