/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { OutputConfig, OutputConfig$zodSchema } from "./outputconfig.js";
import { VariableSpec, VariableSpec$zodSchema } from "./variablespec.js";

/**
 * One version of an evaluator: its judge prompt, model, variables, and rubric.
 */
export type EvaluatorVersionCreate = {
  judge_model: string;
  system_prompt: string;
  output_config?: OutputConfig | null | undefined;
  variables?: Array<VariableSpec> | null | undefined;
};

export const EvaluatorVersionCreate$zodSchema: z.ZodType<
  EvaluatorVersionCreate
> = z.object({
  judge_model: z.string().describe(
    "The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`",
  ),
  output_config: OutputConfig$zodSchema.nullable().optional().describe(
    "The scale points and their labels. Required for a `rating` evaluator. A `binary` evaluator uses the default Correct/Wrong labels unless you set your own",
  ),
  system_prompt: z.string().describe(
    "Judge system prompt. May contain `{{\"{{\"}}variable}}` placeholders",
  ),
  variables: z.array(VariableSpec$zodSchema).nullable().optional().describe(
    "Declared prompt variables. Omit if the prompt has no `{{\"{{\"}}placeholders}}`",
  ),
}).describe(
  "One version of an evaluator: its judge prompt, model, variables, and rubric.",
);
