/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VariableSpec, VariableSpec$zodSchema } from "./variablespec.js";

/**
 * Slim view of the live version for list results, carrying only what the list needs.
 */
export type EvaluatorLiveVersionSummary = {
  uuid: string;
  version_number: number;
  judge_model: string;
  variables?: Array<VariableSpec> | null | undefined;
};

export const EvaluatorLiveVersionSummary$zodSchema: z.ZodType<
  EvaluatorLiveVersionSummary
> = z.object({
  judge_model: z.string().describe(
    "The model that runs the judge, named the way its provider does, for example `openai/gpt-4.1` or `anthropic/claude-sonnet-4`",
  ),
  uuid: z.string().describe("Version ID"),
  variables: z.array(VariableSpec$zodSchema).nullable().optional().describe(
    "Declared prompt variables",
  ),
  version_number: z.int().describe(
    "The version's number. The first version is 1, and it goes up by one for each new version of the evaluator",
  ),
}).describe(
  "Slim view of the live version for list results, carrying only what the list needs.",
);
