/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Status of the job right after you launch it
 */
export const EvaluatorRunLaunchResponseStatus = {
  Queued: "queued",
  InProgress: "in_progress",
} as const;
/**
 * Status of the job right after you launch it
 */
export type EvaluatorRunLaunchResponseStatus = ClosedEnum<
  typeof EvaluatorRunLaunchResponseStatus
>;

export const EvaluatorRunLaunchResponseStatus$zodSchema = z.enum([
  "queued",
  "in_progress",
]).describe("Status of the job right after you launch it");

export type EvaluatorRunLaunchResponse = {
  job_uuid: string;
  status: EvaluatorRunLaunchResponseStatus;
  evaluator_count: number;
  item_count: number;
};

export const EvaluatorRunLaunchResponse$zodSchema: z.ZodType<
  EvaluatorRunLaunchResponse
> = z.object({
  evaluator_count: z.int().describe("How many evaluators the job will run"),
  item_count: z.int().describe("How many items the job will run on"),
  job_uuid: z.string().describe(
    "ID of the evaluator-run job. Poll it for status and results",
  ),
  status: EvaluatorRunLaunchResponseStatus$zodSchema.describe(
    "Status of the job right after you launch it",
  ),
});
