/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  EvaluatorVersionCreate,
  EvaluatorVersionCreate$zodSchema,
} from "./evaluatorversioncreate.js";

/**
 * What the evaluator judges:
 *
 * @remarks
 *
 * - `tts`: TTS audio
 * - `stt`: one transcript
 * - `llm`: a reply with its conversation history
 * - `llm-general`: a standalone input and output pair
 * - `conversation`: a full conversation
 */
export const EvaluatorCreateEvaluatorType = {
  Tts: "tts",
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
} as const;
/**
 * What the evaluator judges:
 *
 * @remarks
 *
 * - `tts`: TTS audio
 * - `stt`: one transcript
 * - `llm`: a reply with its conversation history
 * - `llm-general`: a standalone input and output pair
 * - `conversation`: a full conversation
 */
export type EvaluatorCreateEvaluatorType = ClosedEnum<
  typeof EvaluatorCreateEvaluatorType
>;

export const EvaluatorCreateEvaluatorType$zodSchema = z.enum([
  "tts",
  "stt",
  "llm",
  "llm-general",
  "conversation",
]).describe(
  "What the evaluator judges:\n\n- `tts`: TTS audio\n- `stt`: one transcript\n- `llm`: a reply with its conversation history\n- `llm-general`: a standalone input and output pair\n- `conversation`: a full conversation\n",
);

/**
 * The modality the judge reads:
 *
 * @remarks
 *
 * - `text`
 * - `audio`
 */
export const EvaluatorCreateDataType = {
  Text: "text",
  Audio: "audio",
} as const;
/**
 * The modality the judge reads:
 *
 * @remarks
 *
 * - `text`
 * - `audio`
 */
export type EvaluatorCreateDataType = ClosedEnum<
  typeof EvaluatorCreateDataType
>;

export const EvaluatorCreateDataType$zodSchema = z.enum([
  "text",
  "audio",
]).describe("The modality the judge reads:\n\n- `text`\n- `audio`\n");

/**
 * How the evaluator scores:
 *
 * @remarks
 *
 * - `binary`: pass or fail
 * - `rating`: a numeric score, using the scale in `output_config`
 */
export const EvaluatorCreateOutputType = {
  Binary: "binary",
  Rating: "rating",
} as const;
/**
 * How the evaluator scores:
 *
 * @remarks
 *
 * - `binary`: pass or fail
 * - `rating`: a numeric score, using the scale in `output_config`
 */
export type EvaluatorCreateOutputType = ClosedEnum<
  typeof EvaluatorCreateOutputType
>;

export const EvaluatorCreateOutputType$zodSchema = z.enum([
  "binary",
  "rating",
]).describe(
  "How the evaluator scores:\n\n- `binary`: pass or fail\n- `rating`: a numeric score, using the scale in `output_config`\n",
);

export type EvaluatorCreate = {
  name: string;
  description?: string | null | undefined;
  evaluator_type?: EvaluatorCreateEvaluatorType | undefined;
  data_type?: EvaluatorCreateDataType | undefined;
  output_type?: EvaluatorCreateOutputType | undefined;
  version: EvaluatorVersionCreate;
};

export const EvaluatorCreate$zodSchema: z.ZodType<EvaluatorCreate> = z.object({
  data_type: EvaluatorCreateDataType$zodSchema.default("text").describe(
    "The modality the judge reads:\n\n- `text`\n- `audio`\n",
  ),
  description: z.string().nullable().optional().describe(
    "Description. Omit to leave blank",
  ),
  evaluator_type: EvaluatorCreateEvaluatorType$zodSchema.default("llm")
    .describe(
      "What the evaluator judges:\n\n- `tts`: TTS audio\n- `stt`: one transcript\n- `llm`: a reply with its conversation history\n- `llm-general`: a standalone input and output pair\n- `conversation`: a full conversation\n",
    ),
  name: z.string().describe("Evaluator name, unique within your workspace"),
  output_type: EvaluatorCreateOutputType$zodSchema.default("binary").describe(
    "How the evaluator scores:\n\n- `binary`: pass or fail\n- `rating`: a numeric score, using the scale in `output_config`\n",
  ),
  version: EvaluatorVersionCreate$zodSchema.describe(
    "One version of an evaluator: its judge prompt, model, variables, and rubric.",
  ),
});
