/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvaluatorSetRequest = { evaluator_ids: Array<string> };

export const EvaluatorSetRequest$zodSchema: z.ZodType<EvaluatorSetRequest> = z
  .object({
    evaluator_ids: z.array(z.string()).describe(
      "The full ordered set of evaluators the task should end up linked to, in display order. Missing ones are unlinked, new ones are linked, and the order sets their position. Send an empty list to unlink all. Each must be one you created or a built-in default",
    ),
  });
