/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ExpectedToolCall = {
  tool: string;
  arguments?: { [k: string]: any } | null | undefined;
  accept_any_arguments?: boolean | undefined;
};

export const ExpectedToolCall$zodSchema: z.ZodType<ExpectedToolCall> = z.object(
  {
    accept_any_arguments: z.boolean().default(false).describe(
      "When `true`, only the tool name must match and `arguments` is ignored",
    ),
    arguments: z.record(z.string(), z.any()).nullable().optional().describe(
      "Expected argument values, diffed against the generated call. Omit to expect no arguments",
    ),
    tool: z.string().describe("Name of the tool the agent is expected to call"),
  },
);
