/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  TestRunStatusResponse,
  TestRunStatusResponse$zodSchema,
} from "./testrunstatusresponse.js";

export type GetAgentTestRunStatusAgentTestsRunTaskIdGetRequest = {
  task_id: string;
  xAPIKey?: string | null | undefined;
};

export const GetAgentTestRunStatusAgentTestsRunTaskIdGetRequest$zodSchema:
  z.ZodType<GetAgentTestRunStatusAgentTestsRunTaskIdGetRequest> = z.object({
    task_id: z.string().describe("Test run to poll for status and results"),
    xAPIKey: z.string().nullable().optional(),
  });

export type GetAgentTestRunStatusAgentTestsRunTaskIdGetResponse =
  | TestRunStatusResponse
  | HTTPValidationError;

export const GetAgentTestRunStatusAgentTestsRunTaskIdGetResponse$zodSchema:
  z.ZodType<GetAgentTestRunStatusAgentTestsRunTaskIdGetResponse> = z.union([
    TestRunStatusResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
