/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestRunsResponse,
  AgentTestRunsResponse$zodSchema,
} from "./agenttestrunsresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetRequest$zodSchema:
  z.ZodType<GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetRequest> = z.object({
    agent_uuid: z.string().describe("Agent whose test runs to list"),
    xAPIKey: z.string().nullable().optional(),
  });

export type GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetResponse =
  | AgentTestRunsResponse
  | HTTPValidationError;

export const GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetResponse$zodSchema:
  z.ZodType<GetAgentTestRunsAgentTestsAgentAgentUuidRunsGetResponse> = z.union([
    AgentTestRunsResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
