/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { TestCaseResult, TestCaseResult$zodSchema } from "./testcaseresult.js";

export type GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetRequest =
  {
    task_id: string;
    test_uuid: string;
    model?: string | null | undefined;
    xAPIKey?: string | null | undefined;
  };

export const GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetRequest$zodSchema:
  z.ZodType<
    GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetRequest
  > = z.object({
    model: z.string().describe(
      "Which model's answer to read. Required for a benchmark, which runs every test once per model",
    ).nullable().optional(),
    task_id: z.string().describe("Test run or benchmark the case was run in"),
    test_uuid: z.string().describe(
      "The test whose result to read, as `test_uuid` on the case",
    ),
    xAPIKey: z.string().nullable().optional(),
  });

export type GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetResponse =
  | TestCaseResult
  | HTTPValidationError;

export const GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetResponse$zodSchema:
  z.ZodType<
    GetAgentTestCaseResultAgentTestsRunTaskIdResultsTestUuidGetResponse
  > = z.union([
    TestCaseResult$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
