/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  TestListResponse,
  TestListResponse$zodSchema,
} from "./testlistresponse.js";

export type GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest$zodSchema:
  z.ZodType<GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest> = z
    .object({
      agent_uuid: z.string().describe("Agent whose linked tests to list"),
      xAPIKey: z.string().nullable().optional(),
    });

export type GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse =
  | Array<TestListResponse>
  | HTTPValidationError;

export const GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse$zodSchema:
  z.ZodType<GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse> = z
    .union([
      z.array(TestListResponse$zodSchema).describe("Successful Response"),
      HTTPValidationError$zodSchema,
    ]);
