/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  PaginatedResponseTestListResponse,
  PaginatedResponseTestListResponse$zodSchema,
} from "./paginatedresponsetestlistresponse.js";

/**
 * How to match `q` against the searched fields
 */
export const QMode = {
  Contains: "contains",
  StartsWith: "starts_with",
  EndsWith: "ends_with",
  Exact: "exact",
} as const;
/**
 * How to match `q` against the searched fields
 */
export type QMode = ClosedEnum<typeof QMode>;

export const QMode$zodSchema = z.enum([
  "contains",
  "starts_with",
  "ends_with",
  "exact",
]).describe("How to match `q` against the searched fields");

export type GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest = {
  agent_uuid: string;
  type?: Array<string> | null | undefined;
  q?: string | null | undefined;
  q_mode?: QMode | undefined;
  limit?: number | null | undefined;
  offset?: number | undefined;
  xAPIKey?: string | null | undefined;
};

export const GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest$zodSchema:
  z.ZodType<GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetRequest> = z
    .object({
      agent_uuid: z.string().describe("Agent whose linked tests to list"),
      limit: z.int().describe(
        "Maximum number of items to return. Omit for no limit (all items)",
      ).nullable().optional(),
      offset: z.int().default(0).describe(
        "Number of items to skip before returning results",
      ),
      q: z.string().describe(
        "Case-insensitive search on `name`. Blank is a no-op",
      ).nullable().optional(),
      q_mode: QMode$zodSchema.default("contains").describe(
        "How to match `q` against the searched fields",
      ),
      type: z.array(z.string()).describe(
        "Keep only tests of these types. Repeat the parameter or pass one comma-separated value. Accepts `response`, `tool_call`, `conversation`, `general`",
      ).nullable().optional(),
      xAPIKey: z.string().nullable().optional(),
    });

export type GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse =
  | PaginatedResponseTestListResponse
  | HTTPValidationError;

export const GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse$zodSchema:
  z.ZodType<GetAgentTestsEndpointAgentTestsAgentAgentUuidTestsGetResponse> = z
    .union([
      PaginatedResponseTestListResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
