/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotationTaskResponse,
  AnnotationTaskResponse$zodSchema,
} from "./annotationtaskresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetRequest$zodSchema:
  z.ZodType<GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetRequest> = z
    .object({
      task_uuid: z.string().describe("Task to retrieve"),
      xAPIKey: z.string().nullable().optional(),
    });

export type GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetResponse =
  | AnnotationTaskResponse
  | HTTPValidationError;

export const GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetResponse$zodSchema:
  z.ZodType<GetAnnotationTaskEndpointAnnotationTasksTaskUuidGetResponse> = z
    .union([
      AnnotationTaskResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
