/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentResponse, AgentResponse$zodSchema } from "./agentresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type GetAgentEndpointAgentsAgentUuidGetRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetAgentEndpointAgentsAgentUuidGetRequest$zodSchema: z.ZodType<
  GetAgentEndpointAgentsAgentUuidGetRequest
> = z.object({
  agent_uuid: z.string().describe("The agent to retrieve"),
  xAPIKey: z.string().nullable().optional(),
});

export type GetAgentEndpointAgentsAgentUuidGetResponse =
  | AgentResponse
  | HTTPValidationError;

export const GetAgentEndpointAgentsAgentUuidGetResponse$zodSchema: z.ZodType<
  GetAgentEndpointAgentsAgentUuidGetResponse
> = z.union([
  AgentResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
