/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorDetailResponse,
  EvaluatorDetailResponse$zodSchema,
} from "./evaluatordetailresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetRequest = {
  evaluator_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetRequest$zodSchema:
  z.ZodType<GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetRequest> = z.object({
    evaluator_uuid: z.string().describe("Evaluator to retrieve"),
    xAPIKey: z.string().nullable().optional(),
  });

export type GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetResponse =
  | EvaluatorDetailResponse
  | HTTPValidationError;

export const GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetResponse$zodSchema:
  z.ZodType<GetEvaluatorEndpointEvaluatorsEvaluatorUuidGetResponse> = z.union([
    EvaluatorDetailResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
