/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorRunResponse,
  EvaluatorRunResponse$zodSchema,
} from "./evaluatorrunresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetRequest =
  { task_uuid: string; job_uuid: string; xAPIKey?: string | null | undefined };

export const GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetRequest$zodSchema:
  z.ZodType<
    GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetRequest
  > = z.object({
    job_uuid: z.string().describe("The evaluator run to act on"),
    task_uuid: z.string().describe("Annotation task to act on"),
    xAPIKey: z.string().nullable().optional(),
  });

export type GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetResponse =
  | EvaluatorRunResponse
  | HTTPValidationError;

export const GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetResponse$zodSchema:
  z.ZodType<
    GetEvaluatorRunJobAnnotationTasksTaskUuidEvaluatorRunsJobUuidGetResponse
  > = z.union([
    EvaluatorRunResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
