/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { TestResponse, TestResponse$zodSchema } from "./testresponse.js";

export type GetTestEndpointTestsTestUuidGetRequest = {
  test_uuid: string;
  xAPIKey?: string | null | undefined;
};

export const GetTestEndpointTestsTestUuidGetRequest$zodSchema: z.ZodType<
  GetTestEndpointTestsTestUuidGetRequest
> = z.object({
  test_uuid: z.string().describe("Test to retrieve"),
  xAPIKey: z.string().nullable().optional(),
});

export type GetTestEndpointTestsTestUuidGetResponse =
  | TestResponse
  | HTTPValidationError;

export const GetTestEndpointTestsTestUuidGetResponse$zodSchema: z.ZodType<
  GetTestEndpointTestsTestUuidGetResponse
> = z.union([
  TestResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
