/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ValidationError,
  ValidationError$zodSchema,
} from "./validationerror.js";

export type HTTPValidationError = {
  detail?: Array<ValidationError> | undefined;
};

export const HTTPValidationError$zodSchema: z.ZodType<HTTPValidationError> = z
  .object({
    detail: z.array(ValidationError$zodSchema).optional(),
  });
