/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { TraceIngest, TraceIngest$zodSchema } from "./traceingest.js";
import {
  TraceIngestResponse,
  TraceIngestResponse$zodSchema,
} from "./traceingestresponse.js";

export type IngestTraceTracesPostRequest = {
  xAPIKey?: string | null | undefined;
  body: TraceIngest;
};

export const IngestTraceTracesPostRequest$zodSchema: z.ZodType<
  IngestTraceTracesPostRequest
> = z.object({
  body: TraceIngest$zodSchema,
  xAPIKey: z.string().nullable().optional(),
});

export type IngestTraceTracesPostResponse =
  | TraceIngestResponse
  | HTTPValidationError;

export const IngestTraceTracesPostResponse$zodSchema: z.ZodType<
  IngestTraceTracesPostResponse
> = z.union([
  TraceIngestResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
