/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ItemUpdatePayload = { uuid: string; payload?: any | undefined };

export const ItemUpdatePayload$zodSchema: z.ZodType<ItemUpdatePayload> = z
  .object({
    payload: z.any().optional().describe(
      "The item's new payload. `payload['name']` is still required and must be unique within the task",
    ),
    uuid: z.string().describe("ID of the item to update"),
  });
