/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type JudgeResult = {
  evaluator_uuid?: string | null | undefined;
  reasoning?: string | null | undefined;
  match?: boolean | null | undefined;
  score?: number | null | undefined;
  value_name?: string | null | undefined;
  variable_values?: { [k: string]: any } | null | undefined;
};

export const JudgeResult$zodSchema: z.ZodType<JudgeResult> = z.object({
  evaluator_uuid: z.string().nullable().optional().describe(
    "ID of the evaluator that produced this verdict",
  ),
  match: z.boolean().nullable().optional().describe(
    "Pass/fail verdict, set for binary evaluators",
  ),
  reasoning: z.string().nullable().optional().describe(
    "The judge's rationale for this verdict",
  ),
  score: z.number().nullable().optional().describe(
    "Numeric score, set for rating evaluators",
  ),
  value_name: z.string().nullable().optional().describe(
    "Readable label for the verdict, taken from the run's rubric",
  ),
  variable_values: z.record(z.string(), z.any()).nullable().optional().describe(
    "Values filled into the evaluator prompt's `{{\"{{\"}}variable}}` placeholders for this test case, keyed by variable name",
  ),
});
