/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LabellingJobCreated = {
  uuid: string;
  public_token: string;
  annotator_id: string;
  annotator_name: string;
  item_ids: Array<string>;
  item_count: number;
  evaluator_ids: Array<string>;
  status?: "pending" | undefined;
};

export const LabellingJobCreated$zodSchema: z.ZodType<LabellingJobCreated> = z
  .object({
    annotator_id: z.string().describe(
      "ID of the annotator the job is assigned to",
    ),
    annotator_name: z.string().describe(
      "Name of the annotator the job is assigned to",
    ),
    evaluator_ids: z.array(z.string()).describe(
      "IDs of the evaluators the annotator scores each item on, in the order they are shown",
    ),
    item_count: z.int().describe("How many items the annotator has to label"),
    item_ids: z.array(z.string()).describe(
      "IDs of the items assigned to the annotator",
    ),
    public_token: z.string().describe(
      "Token that opens the annotator's labelling page without signing in",
    ),
    status: z.literal("pending").default("pending").optional().describe(
      "Status of the job right after you create it",
    ),
    uuid: z.string().describe("ID of the labelling job"),
  });
