/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorLinkRequest,
  EvaluatorLinkRequest$zodSchema,
} from "./evaluatorlinkrequest.js";
import {
  EvaluatorLinkResponse,
  EvaluatorLinkResponse$zodSchema,
} from "./evaluatorlinkresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: EvaluatorLinkRequest;
};

export const LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostRequest$zodSchema:
  z.ZodType<LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostRequest> = z
    .object({
      body: EvaluatorLinkRequest$zodSchema,
      task_uuid: z.string().describe("Annotation task to act on"),
      xAPIKey: z.string().nullable().optional(),
    });

export type LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostResponse =
  | EvaluatorLinkResponse
  | HTTPValidationError;

export const LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostResponse$zodSchema:
  z.ZodType<LinkEvaluatorToTaskAnnotationTasksTaskUuidEvaluatorsPostResponse> =
    z.union([
      EvaluatorLinkResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
