/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  RoutersAgentsEvaluatorLinkRequest,
  RoutersAgentsEvaluatorLinkRequest$zodSchema,
} from "./routersagentsevaluatorlinkrequest.js";
import {
  RoutersAgentsEvaluatorLinkResponse,
  RoutersAgentsEvaluatorLinkResponse$zodSchema,
} from "./routersagentsevaluatorlinkresponse.js";

export type LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
  body: RoutersAgentsEvaluatorLinkRequest;
};

export const LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest$zodSchema:
  z.ZodType<LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest> = z
    .object({
      agent_uuid: z.string().describe("The agent to link the evaluators to"),
      body: RoutersAgentsEvaluatorLinkRequest$zodSchema,
      xAPIKey: z.string().nullable().optional(),
    });

export type LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse =
  | RoutersAgentsEvaluatorLinkResponse
  | HTTPValidationError;

export const LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse$zodSchema:
  z.ZodType<LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse> = z
    .union([
      RoutersAgentsEvaluatorLinkResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
