/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorLinkRequest,
  EvaluatorLinkRequest$zodSchema,
} from "./evaluatorlinkrequest.js";
import {
  EvaluatorLinkResponse,
  EvaluatorLinkResponse$zodSchema,
} from "./evaluatorlinkresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
  body: EvaluatorLinkRequest;
};

export const LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest$zodSchema:
  z.ZodType<LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostRequest> = z
    .object({
      agent_uuid: z.string().describe("The agent to link the evaluators to"),
      body: EvaluatorLinkRequest$zodSchema,
      xAPIKey: z.string().nullable().optional(),
    });

export type LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse =
  | EvaluatorLinkResponse
  | HTTPValidationError;

export const LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse$zodSchema:
  z.ZodType<LinkEvaluatorsToAgentAgentsAgentUuidEvaluatorsPostResponse> = z
    .union([
      EvaluatorLinkResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
