/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  PaginatedResponseTestListResponse,
  PaginatedResponseTestListResponse$zodSchema,
} from "./paginatedresponsetestlistresponse.js";

export type ListTestsTestsGetRequest = {
  q?: string | null | undefined;
  limit?: number | null | undefined;
  offset?: number | undefined;
  xAPIKey?: string | null | undefined;
};

export const ListTestsTestsGetRequest$zodSchema: z.ZodType<
  ListTestsTestsGetRequest
> = z.object({
  limit: z.int().describe(
    "Maximum number of items to return. Omit for no limit (all items)",
  ).nullable().optional(),
  offset: z.int().default(0).describe(
    "Number of items to skip before returning results",
  ),
  q: z.string().describe(
    "Case-insensitive substring search on `name`. Blank is a no-op",
  ).nullable().optional(),
  xAPIKey: z.string().nullable().optional(),
});

export type ListTestsTestsGetResponse =
  | PaginatedResponseTestListResponse
  | HTTPValidationError;

export const ListTestsTestsGetResponse$zodSchema: z.ZodType<
  ListTestsTestsGetResponse
> = z.union([
  PaginatedResponseTestListResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
