/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotationTaskResponse,
  AnnotationTaskResponse$zodSchema,
} from "./annotationtaskresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type ListAnnotationTasksAnnotationTasksGetRequest = {
  xAPIKey?: string | null | undefined;
};

export const ListAnnotationTasksAnnotationTasksGetRequest$zodSchema: z.ZodType<
  ListAnnotationTasksAnnotationTasksGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
});

export type ListAnnotationTasksAnnotationTasksGetResponse =
  | Array<AnnotationTaskResponse>
  | HTTPValidationError;

export const ListAnnotationTasksAnnotationTasksGetResponse$zodSchema: z.ZodType<
  ListAnnotationTasksAnnotationTasksGetResponse
> = z.union([
  z.array(AnnotationTaskResponse$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
