/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  TestListResponse,
  TestListResponse$zodSchema,
} from "./testlistresponse.js";

export type ListTestsTestsGetRequest = { xAPIKey?: string | null | undefined };

export const ListTestsTestsGetRequest$zodSchema: z.ZodType<
  ListTestsTestsGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
});

export type ListTestsTestsGetResponse =
  | Array<TestListResponse>
  | HTTPValidationError;

export const ListTestsTestsGetResponse$zodSchema: z.ZodType<
  ListTestsTestsGetResponse
> = z.union([
  z.array(TestListResponse$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
