/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  PaginatedResponseEvaluatorResponse,
  PaginatedResponseEvaluatorResponse$zodSchema,
} from "./paginatedresponseevaluatorresponse.js";

export type ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetRequest = {
  agent_uuid: string;
  q?: string | null | undefined;
  limit?: number | null | undefined;
  offset?: number | undefined;
  xAPIKey?: string | null | undefined;
};

export const ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetRequest$zodSchema:
  z.ZodType<ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetRequest> = z.object({
    agent_uuid: z.string().describe("The agent whose evaluators to list"),
    limit: z.int().describe(
      "Maximum number of items to return. Omit for no limit (all items)",
    ).nullable().optional(),
    offset: z.int().default(0).describe(
      "Number of items to skip before returning results",
    ),
    q: z.string().describe(
      "Case-insensitive substring search on `name`. Blank is a no-op",
    ).nullable().optional(),
    xAPIKey: z.string().nullable().optional(),
  });

export type ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetResponse =
  | PaginatedResponseEvaluatorResponse
  | HTTPValidationError;

export const ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetResponse$zodSchema:
  z.ZodType<ListAgentEvaluatorsAgentsAgentUuidEvaluatorsGetResponse> = z.union([
    PaginatedResponseEvaluatorResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
