/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  RoutersAgentsAgentResponse,
  RoutersAgentsAgentResponse$zodSchema,
} from "./routersagentsagentresponse.js";

export type ListAgentsAgentsGetRequest = {
  xAPIKey?: string | null | undefined;
  xOrgUUID?: string | null | undefined;
};

export const ListAgentsAgentsGetRequest$zodSchema: z.ZodType<
  ListAgentsAgentsGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
  xOrgUUID: z.string().nullable().optional(),
});

export type ListAgentsAgentsGetResponse =
  | Array<RoutersAgentsAgentResponse>
  | HTTPValidationError;

export const ListAgentsAgentsGetResponse$zodSchema: z.ZodType<
  ListAgentsAgentsGetResponse
> = z.union([
  z.array(RoutersAgentsAgentResponse$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
