/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentSummary, AgentSummary$zodSchema } from "./agentsummary.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type ListAgentsAgentsGetRequest = {
  xAPIKey?: string | null | undefined;
};

export const ListAgentsAgentsGetRequest$zodSchema: z.ZodType<
  ListAgentsAgentsGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
});

export type ListAgentsAgentsGetResponse =
  | Array<AgentSummary>
  | HTTPValidationError;

export const ListAgentsAgentsGetResponse$zodSchema: z.ZodType<
  ListAgentsAgentsGetResponse
> = z.union([
  z.array(AgentSummary$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
