/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  RoutersEvaluatorsEvaluatorResponse,
  RoutersEvaluatorsEvaluatorResponse$zodSchema,
} from "./routersevaluatorsevaluatorresponse.js";

/**
 * Filter by what the evaluator judges. Omit for all types
 */
export const ListEvaluatorsEvaluatorsGetEvaluatorType = {
  Tts: "tts",
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
} as const;
/**
 * Filter by what the evaluator judges. Omit for all types
 */
export type ListEvaluatorsEvaluatorsGetEvaluatorType = ClosedEnum<
  typeof ListEvaluatorsEvaluatorsGetEvaluatorType
>;

export const ListEvaluatorsEvaluatorsGetEvaluatorType$zodSchema = z.enum([
  "tts",
  "stt",
  "llm",
  "llm-general",
  "conversation",
]).describe("Filter by what the evaluator judges. Omit for all types");

/**
 * Filter by modality. Omit for all
 */
export const ListEvaluatorsEvaluatorsGetDataType = {
  Text: "text",
  Audio: "audio",
} as const;
/**
 * Filter by modality. Omit for all
 */
export type ListEvaluatorsEvaluatorsGetDataType = ClosedEnum<
  typeof ListEvaluatorsEvaluatorsGetDataType
>;

export const ListEvaluatorsEvaluatorsGetDataType$zodSchema = z.enum([
  "text",
  "audio",
]).describe("Filter by modality. Omit for all");

export type ListEvaluatorsEvaluatorsGetRequest = {
  evaluator_type?: ListEvaluatorsEvaluatorsGetEvaluatorType | null | undefined;
  data_type?: ListEvaluatorsEvaluatorsGetDataType | null | undefined;
  include_defaults?: boolean | undefined;
  xAPIKey?: string | null | undefined;
};

export const ListEvaluatorsEvaluatorsGetRequest$zodSchema: z.ZodType<
  ListEvaluatorsEvaluatorsGetRequest
> = z.object({
  data_type: ListEvaluatorsEvaluatorsGetDataType$zodSchema.nullable().optional()
    .describe("Filter by modality. Omit for all"),
  evaluator_type: ListEvaluatorsEvaluatorsGetEvaluatorType$zodSchema.nullable()
    .optional().describe(
      "Filter by what the evaluator judges. Omit for all types",
    ),
  include_defaults: z.boolean().default(true).describe(
    "When `true`, include the built-in default evaluators alongside the ones you created",
  ),
  xAPIKey: z.string().nullable().optional(),
});

export type ListEvaluatorsEvaluatorsGetResponse =
  | Array<RoutersEvaluatorsEvaluatorResponse>
  | HTTPValidationError;

export const ListEvaluatorsEvaluatorsGetResponse$zodSchema: z.ZodType<
  ListEvaluatorsEvaluatorsGetResponse
> = z.union([
  z.array(RoutersEvaluatorsEvaluatorResponse$zodSchema).describe(
    "Successful Response",
  ),
  HTTPValidationError$zodSchema,
]);
