/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotatorResponse,
  AnnotatorResponse$zodSchema,
} from "./annotatorresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type ListAnnotatorsAnnotatorsGetRequest = {
  xAPIKey?: string | null | undefined;
};

export const ListAnnotatorsAnnotatorsGetRequest$zodSchema: z.ZodType<
  ListAnnotatorsAnnotatorsGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
});

export type ListAnnotatorsAnnotatorsGetResponse =
  | Array<AnnotatorResponse>
  | HTTPValidationError;

export const ListAnnotatorsAnnotatorsGetResponse$zodSchema: z.ZodType<
  ListAnnotatorsAnnotatorsGetResponse
> = z.union([
  z.array(AnnotatorResponse$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
