/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  RoutersTestsTestResponse,
  RoutersTestsTestResponse$zodSchema,
} from "./routersteststestresponse.js";

export type ListTestsTestsGetRequest = { xAPIKey?: string | null | undefined };

export const ListTestsTestsGetRequest$zodSchema: z.ZodType<
  ListTestsTestsGetRequest
> = z.object({
  xAPIKey: z.string().nullable().optional(),
});

export type ListTestsTestsGetResponse =
  | Array<RoutersTestsTestResponse>
  | HTTPValidationError;

export const ListTestsTestsGetResponse$zodSchema: z.ZodType<
  ListTestsTestsGetResponse
> = z.union([
  z.array(RoutersTestsTestResponse$zodSchema).describe("Successful Response"),
  HTTPValidationError$zodSchema,
]);
