/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TestCaseResult, TestCaseResult$zodSchema } from "./testcaseresult.js";

export type ModelResult = {
  model: string;
  success?: boolean | null | undefined;
  message: string;
  total_tests?: number | null | undefined;
  passed?: number | null | undefined;
  failed?: number | null | undefined;
  evaluator_summary?: Array<{ [k: string]: any }> | null | undefined;
  test_results?: Array<TestCaseResult> | null | undefined;
  latency_ms?: { [k: string]: any } | null | undefined;
  cost?: { [k: string]: any } | null | undefined;
  total_tokens?: { [k: string]: any } | null | undefined;
};

export const ModelResult$zodSchema: z.ZodType<ModelResult> = z.object({
  cost: z.record(z.string(), z.any()).nullable().optional().describe(
    "Aggregated cost as `{mean, min, max, count}` (USD)",
  ),
  evaluator_summary: z.array(z.record(z.string(), z.any())).nullable()
    .optional().describe("Aggregate summary for each evaluator for this model"),
  failed: z.int().nullable().optional().describe(
    "Number of test cases that failed",
  ),
  latency_ms: z.record(z.string(), z.any()).nullable().optional().describe(
    "Aggregated latency in milliseconds, as `{p50, p95, p99, count}`",
  ),
  message: z.string().describe("Status or result message for this model"),
  model: z.string().describe("Model name these results are for"),
  passed: z.int().nullable().optional().describe(
    "Number of test cases that passed",
  ),
  success: z.boolean().nullable().optional().describe(
    "Whether this model's run succeeded",
  ),
  test_results: z.array(TestCaseResult$zodSchema).nullable().optional()
    .describe("Results for each test case for this model"),
  total_tests: z.int().nullable().optional().describe(
    "Total test cases for this model",
  ),
  total_tokens: z.record(z.string(), z.any()).nullable().optional().describe(
    "Aggregated token usage as `{mean, min, max, count}`",
  ),
});
