/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Flat summary for one model in a benchmark run-LIST item. The full results
 *
 * @remarks
 * for each case of a model live on the benchmark detail endpoint
 * (`GET /agent-tests/benchmark/{task_id}`), not here.
 */
export type ModelRunSummary = {
  model: string;
  success?: boolean | null | undefined;
  message?: string | undefined;
  total_tests?: number | null | undefined;
  passed?: number | null | undefined;
  failed?: number | null | undefined;
};

export const ModelRunSummary$zodSchema: z.ZodType<ModelRunSummary> = z.object({
  failed: z.int().nullable().optional().describe(
    "Number of test cases that failed for this model",
  ),
  message: z.string().default("").describe(
    "Status or result message for this model",
  ),
  model: z.string().describe("Model name these results are for"),
  passed: z.int().nullable().optional().describe(
    "Number of test cases that passed for this model",
  ),
  success: z.boolean().nullable().optional().describe(
    "Whether this model's run succeeded",
  ),
  total_tests: z.int().nullable().optional().describe(
    "Total test cases for this model",
  ),
}).describe(
  "Flat summary for one model in a benchmark run-LIST item. The full results\nfor each case of a model live on the benchmark detail endpoint\n(`GET /agent-tests/benchmark/{task_id}`), not here.",
);
