/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * One entry in an evaluator's output_config.scale. `value` is bool|number|string
 *
 * @remarks
 * depending on output_type.
 */
export type OutputScaleEntry = {
  value?: any | undefined;
  name: string;
  description?: string | null | undefined;
  color?: string | null | undefined;
};

export const OutputScaleEntry$zodSchema: z.ZodType<OutputScaleEntry> = z.object(
  {
    color: z.string().nullable().optional().describe(
      "Color to show for this level. Omit for the default",
    ),
    description: z.string().nullable().optional().describe(
      "Rubric text for this level, added to the judge prompt. Omit to leave this level undescribed",
    ),
    name: z.string().describe("Short label for this scale point"),
    value: z.any().optional().describe(
      "The value for this scale point. Use a boolean for a `binary` evaluator, a number for a `rating` one",
    ),
  },
).describe(
  "One entry in an evaluator's output_config.scale. `value` is bool|number|string\ndepending on output_type.",
);
