/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OutputScaleEntry,
  OutputScaleEntry$zodSchema,
} from "./outputscaleentry.js";

export type OutputConfig = {
  scale?: Array<OutputScaleEntry> | null | undefined;
};

export const OutputConfig$zodSchema: z.ZodType<OutputConfig> = z.object({
  scale: z.array(OutputScaleEntry$zodSchema).nullable().optional().describe(
    "The ordered scale points that make up the rubric, each with its label",
  ),
});
