/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TestListResponse,
  TestListResponse$zodSchema,
} from "./testlistresponse.js";

export type PaginatedResponseTestListResponse = {
  items: Array<TestListResponse>;
  total: number;
  limit?: number | null | undefined;
  offset?: number | undefined;
};

export const PaginatedResponseTestListResponse$zodSchema: z.ZodType<
  PaginatedResponseTestListResponse
> = z.object({
  items: z.array(TestListResponse$zodSchema).describe("The page of results"),
  limit: z.int().nullable().optional().describe(
    "The applied `limit` (null when unbounded)",
  ),
  offset: z.int().default(0).describe("The applied `offset`"),
  total: z.int().describe(
    "Total number of items matching the query, before pagination",
  ),
});
