/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentSummary, AgentSummary$zodSchema } from "./agentsummary.js";

export type PaginatedResponseAgentSummary = {
  items: Array<AgentSummary>;
  total: number;
  limit?: number | null | undefined;
  offset?: number | undefined;
};

export const PaginatedResponseAgentSummary$zodSchema: z.ZodType<
  PaginatedResponseAgentSummary
> = z.object({
  items: z.array(AgentSummary$zodSchema).describe("The page of results"),
  limit: z.int().nullable().optional().describe(
    "The applied `limit` (null when unbounded)",
  ),
  offset: z.int().default(0).describe("The applied `offset`"),
  total: z.int().describe(
    "Total number of items matching the query, before pagination",
  ),
});
