/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PaginationMeta = { total: number; limit: number; offset: number };

export const PaginationMeta$zodSchema: z.ZodType<PaginationMeta> = z.object({
  limit: z.int().describe("Maximum number of items returned in this page"),
  offset: z.int().describe("Number of items skipped before this page"),
  total: z.int().describe("Total number of items that match, across all pages"),
});
