/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RoutersEvaluatorsEvaluatorResponse,
  RoutersEvaluatorsEvaluatorResponse$zodSchema,
} from "./routersevaluatorsevaluatorresponse.js";

export type PaginatedResponseEvaluatorResponse = {
  items: Array<RoutersEvaluatorsEvaluatorResponse>;
  total: number;
  limit?: number | null | undefined;
  offset?: number | undefined;
};

export const PaginatedResponseEvaluatorResponse$zodSchema: z.ZodType<
  PaginatedResponseEvaluatorResponse
> = z.object({
  items: z.array(RoutersEvaluatorsEvaluatorResponse$zodSchema).describe(
    "The page of results",
  ),
  limit: z.int().nullable().optional().describe(
    "The applied `limit` (null when unbounded)",
  ),
  offset: z.int().default(0).describe("The applied `offset`"),
  total: z.int().describe(
    "Total number of items matching the query, before pagination",
  ),
});
