/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestRunListItem,
  AgentTestRunListItem$zodSchema,
} from "./agenttestrunlistitem.js";

export type PaginatedResponseAgentTestRunListItem = {
  items: Array<AgentTestRunListItem>;
  total: number;
  limit?: number | null | undefined;
  offset?: number | undefined;
};

export const PaginatedResponseAgentTestRunListItem$zodSchema: z.ZodType<
  PaginatedResponseAgentTestRunListItem
> = z.object({
  items: z.array(AgentTestRunListItem$zodSchema).describe(
    "The page of results",
  ),
  limit: z.int().nullable().optional().describe(
    "The applied `limit` (null when unbounded)",
  ),
  offset: z.int().default(0).describe("The applied `offset`"),
  total: z.int().describe(
    "Total number of items matching the query, before pagination",
  ),
});
