/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ResolveAgentNamesRequest = { names: Array<string> };

export const ResolveAgentNamesRequest$zodSchema: z.ZodType<
  ResolveAgentNamesRequest
> = z.object({
  names: z.array(z.string()).describe("Agent names to resolve to IDs"),
});
