/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  ResolveAgentNamesRequest,
  ResolveAgentNamesRequest$zodSchema,
} from "./resolveagentnamesrequest.js";
import {
  ResolveAgentNamesResponse,
  ResolveAgentNamesResponse$zodSchema,
} from "./resolveagentnamesresponse.js";

export type ResolveAgentNamesAgentsResolvePostRequest = {
  xAPIKey?: string | null | undefined;
  xOrgUUID?: string | null | undefined;
  body: ResolveAgentNamesRequest;
};

export const ResolveAgentNamesAgentsResolvePostRequest$zodSchema: z.ZodType<
  ResolveAgentNamesAgentsResolvePostRequest
> = z.object({
  body: ResolveAgentNamesRequest$zodSchema,
  xAPIKey: z.string().nullable().optional(),
  xOrgUUID: z.string().nullable().optional(),
});

export type ResolveAgentNamesAgentsResolvePostResponse =
  | ResolveAgentNamesResponse
  | HTTPValidationError;

export const ResolveAgentNamesAgentsResolvePostResponse$zodSchema: z.ZodType<
  ResolveAgentNamesAgentsResolvePostResponse
> = z.union([
  ResolveAgentNamesResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
