/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ResolveAgentNamesResponse = {
  resolved: { [k: string]: string };
  not_found: Array<string>;
};

export const ResolveAgentNamesResponse$zodSchema: z.ZodType<
  ResolveAgentNamesResponse
> = z.object({
  not_found: z.array(z.string()).describe(
    "Names with no matching agent in your workspace",
  ),
  resolved: z.record(z.string(), z.string()).describe(
    "Map of name to agent ID for each name that matched",
  ),
});
