/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * What the test checks:
 *
 * @remarks
 * - `response`: judges the reply the agent generates
 * - `tool_call`: checks the tool calls the agent makes
 * - `conversation`: judges the full conversation after the agent replies
 */
export const RoutersAgentTestsTestResponseType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
/**
 * What the test checks:
 *
 * @remarks
 * - `response`: judges the reply the agent generates
 * - `tool_call`: checks the tool calls the agent makes
 * - `conversation`: judges the full conversation after the agent replies
 */
export type RoutersAgentTestsTestResponseType = ClosedEnum<
  typeof RoutersAgentTestsTestResponseType
>;

export const RoutersAgentTestsTestResponseType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]).describe(
  "What the test checks:\n- `response`: judges the reply the agent generates\n- `tool_call`: checks the tool calls the agent makes\n- `conversation`: judges the full conversation after the agent replies",
);

export type RoutersAgentTestsTestResponse = {
  uuid: string;
  name: string;
  type: RoutersAgentTestsTestResponseType;
  config?: { [k: string]: any } | null | undefined;
  created_at: string;
  updated_at: string;
};

export const RoutersAgentTestsTestResponse$zodSchema: z.ZodType<
  RoutersAgentTestsTestResponse
> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "Test configuration",
  ),
  created_at: z.string().describe("When the test was created (ISO 8601 UTC)"),
  name: z.string().describe("Name of the test"),
  type: RoutersAgentTestsTestResponseType$zodSchema.describe(
    "What the test checks:\n- `response`: judges the reply the agent generates\n- `tool_call`: checks the tool calls the agent makes\n- `conversation`: judges the full conversation after the agent replies",
  ),
  updated_at: z.string().describe(
    "When the test was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("Test ID"),
});
