/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RoutersTestsEvaluatorRef = {
  evaluator_uuid: string;
  variable_values?: { [k: string]: any } | null | undefined;
};

export const RoutersTestsEvaluatorRef$zodSchema: z.ZodType<
  RoutersTestsEvaluatorRef
> = z.object({
  evaluator_uuid: z.string().describe("Evaluator to attach to the test"),
  variable_values: z.record(z.string(), z.any()).nullable().optional().describe(
    "Values for the evaluator's `{{\"{{\"}}placeholder}}` variables, pinned on this test. Omit to inherit the evaluator version's defaults",
  ),
});
