/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export const RoutersAgentsAgentResponseType = {
  Agent: "agent",
  Connection: "connection",
} as const;
/**
 * - `agent`: built inside Calibrate
 *
 * @remarks
 * - `connection`: your existing agent connected to Calibrate
 */
export type RoutersAgentsAgentResponseType = ClosedEnum<
  typeof RoutersAgentsAgentResponseType
>;

export const RoutersAgentsAgentResponseType$zodSchema = z.enum([
  "agent",
  "connection",
]).describe(
  "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
);

export type RoutersAgentsAgentResponse = {
  uuid: string;
  name: string;
  type: RoutersAgentsAgentResponseType;
  config?: { [k: string]: any } | null | undefined;
  created_at: string;
  updated_at: string;
};

export const RoutersAgentsAgentResponse$zodSchema: z.ZodType<
  RoutersAgentsAgentResponse
> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "Agent configuration",
  ),
  created_at: z.string().describe("When the agent was created (ISO 8601 UTC)"),
  name: z.string().describe("Name of the agent"),
  type: RoutersAgentsAgentResponseType$zodSchema.describe(
    "- `agent`: built inside Calibrate\n- `connection`: your existing agent connected to Calibrate",
  ),
  updated_at: z.string().describe(
    "When the agent was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("ID of the agent"),
});
