/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RoutersAgentsEvaluatorLinkResponse = {
  message: string;
  linked: Array<string>;
  already_linked: Array<string>;
};

export const RoutersAgentsEvaluatorLinkResponse$zodSchema: z.ZodType<
  RoutersAgentsEvaluatorLinkResponse
> = z.object({
  already_linked: z.array(z.string()).describe(
    "Evaluator IDs skipped because they were already linked",
  ),
  linked: z.array(z.string()).describe(
    "Evaluator IDs newly linked by this request",
  ),
  message: z.string().describe("Confirmation that the evaluators were linked"),
});
