/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export const RoutersTestsTestResponseType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export type RoutersTestsTestResponseType = ClosedEnum<
  typeof RoutersTestsTestResponseType
>;

export const RoutersTestsTestResponseType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]).describe(
  "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n",
);

export type RoutersTestsTestResponse = {
  uuid: string;
  name: string;
  type: RoutersTestsTestResponseType;
  config?: { [k: string]: any } | null | undefined;
  created_at: string;
  updated_at: string;
  evaluators?: Array<{ [k: string]: any }> | undefined;
};

export const RoutersTestsTestResponse$zodSchema: z.ZodType<
  RoutersTestsTestResponse
> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "The stored config: `history`, `evaluation`, and an optional `settings`",
  ),
  created_at: z.string().describe("When the test was created (ISO 8601 UTC)"),
  evaluators: z.array(z.record(z.string(), z.any())).optional().describe(
    "Linked evaluators, resolved to their current live version at read time",
  ),
  name: z.string().describe("Name of the test"),
  type: RoutersTestsTestResponseType$zodSchema.describe(
    "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n",
  ),
  updated_at: z.string().describe(
    "When the test was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("Unique ID for the test"),
});
