/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  EvaluatorLiveVersionSummary,
  EvaluatorLiveVersionSummary$zodSchema,
} from "./evaluatorliveversionsummary.js";

/**
 * What the evaluator judges:
 *
 * @remarks
 *
 * - `tts`: TTS audio
 * - `stt`: one transcript
 * - `llm`: a reply with its conversation history
 * - `llm-general`: a standalone input and output pair
 * - `conversation`: a full conversation
 */
export const RoutersEvaluatorsEvaluatorResponseEvaluatorType = {
  Tts: "tts",
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
} as const;
/**
 * What the evaluator judges:
 *
 * @remarks
 *
 * - `tts`: TTS audio
 * - `stt`: one transcript
 * - `llm`: a reply with its conversation history
 * - `llm-general`: a standalone input and output pair
 * - `conversation`: a full conversation
 */
export type RoutersEvaluatorsEvaluatorResponseEvaluatorType = ClosedEnum<
  typeof RoutersEvaluatorsEvaluatorResponseEvaluatorType
>;

export const RoutersEvaluatorsEvaluatorResponseEvaluatorType$zodSchema = z.enum(
  [
    "tts",
    "stt",
    "llm",
    "llm-general",
    "conversation",
  ],
).describe(
  "What the evaluator judges:\n\n- `tts`: TTS audio\n- `stt`: one transcript\n- `llm`: a reply with its conversation history\n- `llm-general`: a standalone input and output pair\n- `conversation`: a full conversation\n",
);

/**
 * The modality the judge reads:
 *
 * @remarks
 *
 * - `text`
 * - `audio`
 */
export const RoutersEvaluatorsEvaluatorResponseDataType = {
  Text: "text",
  Audio: "audio",
} as const;
/**
 * The modality the judge reads:
 *
 * @remarks
 *
 * - `text`
 * - `audio`
 */
export type RoutersEvaluatorsEvaluatorResponseDataType = ClosedEnum<
  typeof RoutersEvaluatorsEvaluatorResponseDataType
>;

export const RoutersEvaluatorsEvaluatorResponseDataType$zodSchema = z.enum([
  "text",
  "audio",
]).describe("The modality the judge reads:\n\n- `text`\n- `audio`\n");

/**
 * How the evaluator scores:
 *
 * @remarks
 *
 * - `binary`: pass or fail
 * - `rating`: a numeric score, using the scale in `output_config`
 */
export const RoutersEvaluatorsEvaluatorResponseOutputType = {
  Binary: "binary",
  Rating: "rating",
} as const;
/**
 * How the evaluator scores:
 *
 * @remarks
 *
 * - `binary`: pass or fail
 * - `rating`: a numeric score, using the scale in `output_config`
 */
export type RoutersEvaluatorsEvaluatorResponseOutputType = ClosedEnum<
  typeof RoutersEvaluatorsEvaluatorResponseOutputType
>;

export const RoutersEvaluatorsEvaluatorResponseOutputType$zodSchema = z.enum([
  "binary",
  "rating",
]).describe(
  "How the evaluator scores:\n\n- `binary`: pass or fail\n- `rating`: a numeric score, using the scale in `output_config`\n",
);

export type RoutersEvaluatorsEvaluatorResponse = {
  uuid: string;
  name: string;
  description?: string | null | undefined;
  evaluator_type: RoutersEvaluatorsEvaluatorResponseEvaluatorType;
  data_type: RoutersEvaluatorsEvaluatorResponseDataType;
  output_type: RoutersEvaluatorsEvaluatorResponseOutputType;
  is_default: boolean;
  slug?: string | null | undefined;
  live_version_id?: string | null | undefined;
  created_at: string;
  updated_at: string;
  live_version?: EvaluatorLiveVersionSummary | null | undefined;
};

export const RoutersEvaluatorsEvaluatorResponse$zodSchema: z.ZodType<
  RoutersEvaluatorsEvaluatorResponse
> = z.object({
  created_at: z.string().describe(
    "When the evaluator was created (ISO 8601 UTC)",
  ),
  data_type: RoutersEvaluatorsEvaluatorResponseDataType$zodSchema.describe(
    "The modality the judge reads:\n\n- `text`\n- `audio`\n",
  ),
  description: z.string().nullable().optional().describe(
    "What the evaluator checks",
  ),
  evaluator_type: RoutersEvaluatorsEvaluatorResponseEvaluatorType$zodSchema
    .describe(
      "What the evaluator judges:\n\n- `tts`: TTS audio\n- `stt`: one transcript\n- `llm`: a reply with its conversation history\n- `llm-general`: a standalone input and output pair\n- `conversation`: a full conversation\n",
    ),
  is_default: z.boolean().describe(
    "True for a built-in default evaluator, which you can't edit. False for an evaluator you created, which you can edit and add versions to",
  ),
  live_version: EvaluatorLiveVersionSummary$zodSchema.nullable().optional()
    .describe("The version that is currently live"),
  live_version_id: z.string().nullable().optional().describe(
    "ID of the version that is currently live",
  ),
  name: z.string().describe("Evaluator name"),
  output_type: RoutersEvaluatorsEvaluatorResponseOutputType$zodSchema.describe(
    "How the evaluator scores:\n\n- `binary`: pass or fail\n- `rating`: a numeric score, using the scale in `output_config`\n",
  ),
  slug: z.string().nullable().optional().describe(
    "Stable slug for a built-in default evaluator",
  ),
  updated_at: z.string().describe(
    "When the evaluator was last updated (ISO 8601 UTC)",
  ),
  uuid: z.string().describe("Evaluator ID"),
});
