/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentTestRunCreateResponse,
  AgentTestRunCreateResponse$zodSchema,
} from "./agenttestruncreateresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { RunTestRequest, RunTestRequest$zodSchema } from "./runtestrequest.js";

export type RunAgentTestAgentTestsAgentAgentUuidRunPostRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
  body: RunTestRequest;
};

export const RunAgentTestAgentTestsAgentAgentUuidRunPostRequest$zodSchema:
  z.ZodType<RunAgentTestAgentTestsAgentAgentUuidRunPostRequest> = z.object({
    agent_uuid: z.string().describe("Agent to test"),
    body: RunTestRequest$zodSchema,
    xAPIKey: z.string().nullable().optional(),
  });

export type RunAgentTestAgentTestsAgentAgentUuidRunPostResponse =
  | AgentTestRunCreateResponse
  | HTTPValidationError;

export const RunAgentTestAgentTestsAgentAgentUuidRunPostResponse$zodSchema:
  z.ZodType<RunAgentTestAgentTestsAgentAgentUuidRunPostResponse> = z.union([
    AgentTestRunCreateResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
