/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * One evaluator on a run-LIST row: just enough to name it and open it.
 *
 * @remarks
 * The rubric, prompt and version live on the run-DETAIL endpoint.
 */
export type RunListEvaluator = {
  uuid?: string | null | undefined;
  name: string;
};

export const RunListEvaluator$zodSchema: z.ZodType<RunListEvaluator> = z.object(
  {
    name: z.string().describe("Name of the evaluator"),
    uuid: z.string().nullable().optional().describe(
      "ID of the evaluator. Absent for the `Tool call` entry, which is not an evaluator in the library",
    ),
  },
).describe(
  "One evaluator on a run-LIST row: just enough to name it and open it.\nThe rubric, prompt and version live on the run-DETAIL endpoint.",
);
