/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RunTestRequest = { test_uuids?: Array<string> | null | undefined };

export const RunTestRequest$zodSchema: z.ZodType<RunTestRequest> = z.object({
  test_uuids: z.array(z.string()).nullable().optional().describe(
    "Tests to run. Omit to run all tests linked to the agent",
  ),
});
