/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BatchRunRequest,
  BatchRunRequest$zodSchema,
} from "./batchrunrequest.js";
import {
  BatchTestRunResponse,
  BatchTestRunResponse$zodSchema,
} from "./batchtestrunresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type RunTestsBatchAgentTestsRunPostRequest = {
  xAPIKey?: string | null | undefined;
  xOrgUUID?: string | null | undefined;
  body?: BatchRunRequest | null | undefined;
};

export const RunTestsBatchAgentTestsRunPostRequest$zodSchema: z.ZodType<
  RunTestsBatchAgentTestsRunPostRequest
> = z.object({
  body: BatchRunRequest$zodSchema.nullable().optional(),
  xAPIKey: z.string().nullable().optional(),
  xOrgUUID: z.string().nullable().optional(),
});

export type RunTestsBatchAgentTestsRunPostResponse =
  | BatchTestRunResponse
  | HTTPValidationError;

export const RunTestsBatchAgentTestsRunPostResponse$zodSchema: z.ZodType<
  RunTestsBatchAgentTestsRunPostResponse
> = z.union([
  BatchTestRunResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
