/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorSetRequest,
  EvaluatorSetRequest$zodSchema,
} from "./evaluatorsetrequest.js";
import {
  EvaluatorSetResponse,
  EvaluatorSetResponse$zodSchema,
} from "./evaluatorsetresponse.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: EvaluatorSetRequest;
};

export const SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutRequest$zodSchema:
  z.ZodType<SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutRequest> = z
    .object({
      body: EvaluatorSetRequest$zodSchema,
      task_uuid: z.string().describe("Annotation task to act on"),
      xAPIKey: z.string().nullable().optional(),
    });

export type SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutResponse =
  | EvaluatorSetResponse
  | HTTPValidationError;

export const SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutResponse$zodSchema:
  z.ZodType<SetTaskEvaluatorsAnnotationTasksTaskUuidEvaluatorsPutResponse> = z
    .union([
      EvaluatorSetResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
