/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EvaluatorRunLaunchResponse,
  EvaluatorRunLaunchResponse$zodSchema,
} from "./evaluatorrunlaunchresponse.js";
import {
  EvaluatorRunStartRequest,
  EvaluatorRunStartRequest$zodSchema,
} from "./evaluatorrunstartrequest.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostRequest = {
  task_uuid: string;
  xAPIKey?: string | null | undefined;
  body: EvaluatorRunStartRequest;
};

export const StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostRequest$zodSchema:
  z.ZodType<StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostRequest> =
    z.object({
      body: EvaluatorRunStartRequest$zodSchema,
      task_uuid: z.string().describe("Annotation task to act on"),
      xAPIKey: z.string().nullable().optional(),
    });

export type StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostResponse =
  | EvaluatorRunLaunchResponse
  | HTTPValidationError;

export const StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostResponse$zodSchema:
  z.ZodType<StartEvaluatorRunAnnotationTasksTaskUuidEvaluatorRunsPostResponse> =
    z.union([
      EvaluatorRunLaunchResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
