/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";
import {
  HumanAgreementBlock,
  HumanAgreementBlock$zodSchema,
  HumanAgreementBlock$zodSchemaOutbound,
} from "./humanagreementblock.js";

export type TaskAgreementResponse = {
  task_id: string;
  bucket: string;
  days: number;
  human_human: HumanAgreementBlock;
  evaluators: Array<{ [k: string]: any }>;
  AdditionalProperties?: { [k: string]: any };
};

export const TaskAgreementResponse$zodSchema: z.ZodType<TaskAgreementResponse> =
  collectExtraKeys$(
    z.object({
      bucket: z.string().describe("Time bucket used for the trend series"),
      days: z.int().describe("Length of the trailing window in days"),
      evaluators: z.array(z.record(z.string(), z.any())).describe(
        "Agreement between each evaluator and the annotators, one entry per linked evaluator",
      ),
      human_human: HumanAgreementBlock$zodSchema,
      task_id: z.string().describe("ID of the task"),
    }).catchall(z.any()),
    "AdditionalProperties",
    true,
  );

export const TaskAgreementResponse$zodSchemaOutbound: z.ZodType<any> = z.object(
  {
    AdditionalProperties: z.record(z.string(), z.any()).optional(),
    bucket: z.string(),
    days: z.int(),
    evaluators: z.array(z.record(z.string(), z.any())),
    human_human: HumanAgreementBlock$zodSchemaOutbound,
    task_id: z.string(),
  },
).transform((v) => {
  const { AdditionalProperties, ...rest } = v;
  return {
    ...rest,
    ...AdditionalProperties,
  };
});
