/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaskStatus = {
  Queued: "queued",
  InProgress: "in_progress",
  Cancelled: "cancelled",
  Done: "done",
  Failed: "failed",
} as const;
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

export const TaskStatus$zodSchema = z.enum([
  "queued",
  "in_progress",
  "cancelled",
  "done",
  "failed",
]);
