/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { PaginationMeta, PaginationMeta$zodSchema } from "./paginationmeta.js";

/**
 * Type of the task
 */
export const TaskType = {
  Stt: "stt",
  Llm: "llm",
  LlmGeneral: "llm-general",
  Conversation: "conversation",
  Tts: "tts",
} as const;
/**
 * Type of the task
 */
export type TaskType = ClosedEnum<typeof TaskType>;

export const TaskType$zodSchema = z.enum([
  "stt",
  "llm",
  "llm-general",
  "conversation",
  "tts",
]).describe("Type of the task");

export type TaskSummaryResponse = {
  task_id: string;
  task_type: TaskType;
  evaluators: Array<{ [k: string]: any }>;
  annotators: Array<{ [k: string]: any }>;
  rows: Array<{ [k: string]: any }>;
  item_comments?: { [k: string]: any } | null | undefined;
  pagination: PaginationMeta;
  AdditionalProperties?: { [k: string]: any };
};

export const TaskSummaryResponse$zodSchema: z.ZodType<TaskSummaryResponse> =
  collectExtraKeys$(
    z.object({
      annotators: z.array(z.record(z.string(), z.any())).describe(
        "The annotators who labelled or commented on items in the task, stable across pages",
      ),
      evaluators: z.array(z.record(z.string(), z.any())).describe(
        "The task's evaluators, stable across pages, each with its live rubric",
      ),
      item_comments: z.record(z.string(), z.any()).nullable().optional()
        .describe("Annotator comments, keyed by item ID"),
      pagination: PaginationMeta$zodSchema,
      rows: z.array(z.record(z.string(), z.any())).describe(
        "One row per item, evaluator, and version on this page, with the evaluator's value and each annotator's label",
      ),
      task_id: z.string().describe("ID of the task"),
      task_type: TaskType$zodSchema.describe("Type of the task"),
    }).catchall(z.any()),
    "AdditionalProperties",
    true,
  );

export const TaskSummaryResponse$zodSchemaOutbound: z.ZodType<any> = z.object({
  AdditionalProperties: z.record(z.string(), z.any()).optional(),
  annotators: z.array(z.record(z.string(), z.any())),
  evaluators: z.array(z.record(z.string(), z.any())),
  item_comments: z.nullable(z.record(z.string(), z.any())).optional(),
  pagination: PaginationMeta$zodSchema,
  rows: z.array(z.record(z.string(), z.any())),
  task_id: z.string(),
  task_type: TaskType$zodSchema,
}).transform((v) => {
  const { AdditionalProperties, ...rest } = v;
  return {
    ...rest,
    ...AdditionalProperties,
  };
});
