/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  TaskSummaryResponse,
  TaskSummaryResponse$zodSchema,
} from "./tasksummaryresponse.js";

/**
 * Sort direction
 */
export const Order = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort direction
 */
export type Order = ClosedEnum<typeof Order>;

export const Order$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("Sort direction");

export type TaskSummaryAnnotationTasksTaskUuidSummaryGetRequest = {
  task_uuid: string;
  item_id?: string | null | undefined;
  live_only?: boolean | undefined;
  q?: string | null | undefined;
  sort_by?: string | undefined;
  order?: Order | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  xAPIKey?: string | null | undefined;
};

export const TaskSummaryAnnotationTasksTaskUuidSummaryGetRequest$zodSchema:
  z.ZodType<TaskSummaryAnnotationTasksTaskUuidSummaryGetRequest> = z.object({
    item_id: z.string().describe(
      "Filter rows to a single item. The full task-wide annotator union is still returned in `annotators`",
    ).nullable().optional(),
    limit: z.int().default(50).describe("Maximum number of items to return"),
    live_only: z.boolean().default(false).describe(
      "When true, emit only one row for each (item, evaluator) pair using the evaluator's live version. Versions other than the live one that have runs are excluded",
    ),
    offset: z.int().default(0).describe(
      "Number of items to skip before returning results",
    ),
    order: Order$zodSchema.default("desc").describe("Sort direction"),
    q: z.string().describe(
      "Case-insensitive substring search on `payload.name`. Blank is a no-op",
    ).nullable().optional(),
    sort_by: z.string().default("created_at").describe(
      "Sort key for the results",
    ),
    task_uuid: z.string().describe("Annotation task to act on"),
    xAPIKey: z.string().nullable().optional(),
  });

export type TaskSummaryAnnotationTasksTaskUuidSummaryGetResponse =
  | TaskSummaryResponse
  | HTTPValidationError;

export const TaskSummaryAnnotationTasksTaskUuidSummaryGetResponse$zodSchema:
  z.ZodType<TaskSummaryAnnotationTasksTaskUuidSummaryGetResponse> = z.union([
    TaskSummaryResponse$zodSchema,
    HTTPValidationError$zodSchema,
  ]);
