/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";
import { TestCaseResult, TestCaseResult$zodSchema } from "./testcaseresult.js";
import {
  TestRunEvaluator,
  TestRunEvaluator$zodSchema,
} from "./testrunevaluator.js";

export type TestRunStatusResponse = {
  task_id: string;
  name: string;
  status: TaskStatus;
  test_uuids?: Array<string> | null | undefined;
  total_tests?: number | null | undefined;
  passed?: number | null | undefined;
  failed?: number | null | undefined;
  latency_ms?: { [k: string]: any } | null | undefined;
  cost?: { [k: string]: any } | null | undefined;
  total_tokens?: { [k: string]: any } | null | undefined;
  evaluators?: Array<TestRunEvaluator> | null | undefined;
  results?: Array<TestCaseResult> | null | undefined;
  unanswered_tests?: number | null | undefined;
  stopped_early?: boolean | undefined;
  aborted?: boolean | undefined;
  error?: boolean | undefined;
  is_public?: boolean | undefined;
  share_token?: string | null | undefined;
};

export const TestRunStatusResponse$zodSchema: z.ZodType<TestRunStatusResponse> =
  z.object({
    aborted: z.boolean().default(false).describe(
      "Whether a user stopped this run before it finished. The results collected up to that point are kept, and test cases that never ran are counted neither as passed nor as failed",
    ),
    cost: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated cost as `{mean, min, max, count}` (USD)",
    ),
    error: z.boolean().default(false).describe("True if the run failed"),
    evaluators: z.array(TestRunEvaluator$zodSchema).nullable().optional()
      .describe(
        "The evaluators used in this run. Each verdict in `judge_results` links to one of these by `evaluator_uuid`",
      ),
    failed: z.int().nullable().optional().describe(
      "Number of test cases that failed",
    ),
    is_public: z.boolean().default(false).describe(
      "Whether the run is shared publicly",
    ),
    latency_ms: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated response latency in milliseconds, as `{p50, p95, p99, count}`",
    ),
    name: z.string().describe(
      "Name of the run. A run nobody has renamed shows its number instead, such as `Run 1` for a test run or `Benchmark 1` for a benchmark",
    ),
    passed: z.int().nullable().optional().describe(
      "Number of test cases that passed",
    ),
    results: z.array(TestCaseResult$zodSchema).nullable().optional().describe(
      "Results for each test case",
    ),
    share_token: z.string().nullable().optional().describe(
      "Token for building the public share URL",
    ),
    status: TaskStatus$zodSchema,
    stopped_early: z.boolean().default(false).describe(
      "Whether the run stopped before starting every test case, after too many failed in a row",
    ),
    task_id: z.string().describe("Test run job ID"),
    test_uuids: z.array(z.string()).nullable().optional().describe(
      "IDs of the tests this run executed, in run order",
    ),
    total_tests: z.int().nullable().optional().describe(
      "Total number of test cases",
    ),
    total_tokens: z.record(z.string(), z.any()).nullable().optional().describe(
      "Aggregated token usage as `{mean, min, max, count}`",
    ),
    unanswered_tests: z.int().nullable().optional().describe(
      "Number of test cases that produced no answer because the agent or the judge could not be reached, which makes the pass rate an unfair measure of the agent",
    ),
  });
