/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TestRunEvaluatorOutputType = {
  Binary: "binary",
  Rating: "rating",
} as const;
export type TestRunEvaluatorOutputType = ClosedEnum<
  typeof TestRunEvaluatorOutputType
>;

export const TestRunEvaluatorOutputType$zodSchema = z.enum([
  "binary",
  "rating",
]);

export type TestRunEvaluator = {
  uuid?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  output_type?: TestRunEvaluatorOutputType | null | undefined;
  output_config?: { [k: string]: any } | null | undefined;
  scale_min?: number | null | undefined;
  scale_max?: number | null | undefined;
  version_number?: number | null | undefined;
};

export const TestRunEvaluator$zodSchema: z.ZodType<TestRunEvaluator> = z.object(
  {
    description: z.string().nullable().optional().describe(
      "What the evaluator checks",
    ),
    name: z.string().nullable().optional().describe("Name of the evaluator"),
    output_config: z.record(z.string(), z.any()).nullable().optional().describe(
      "The rubric: the scale values, labels, and colors a verdict maps to",
    ),
    output_type: TestRunEvaluatorOutputType$zodSchema.nullable().optional()
      .describe(
        "The shape of the verdict:\n- `binary`: a pass/fail verdict\n- `rating`: a numeric score",
      ),
    scale_max: z.number().nullable().optional().describe(
      "Highest value on a rating scale",
    ),
    scale_min: z.number().nullable().optional().describe(
      "Lowest value on a rating scale",
    ),
    uuid: z.string().nullable().optional().describe("ID of the evaluator"),
    version_number: z.int().nullable().optional().describe(
      "The evaluator version this run used",
    ),
  },
);
