/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OutputType = {
  Binary: "binary",
  Rating: "rating",
} as const;
export type OutputType = ClosedEnum<typeof OutputType>;

export const OutputType$zodSchema = z.enum([
  "binary",
  "rating",
]);

export type TestRunEvaluator = {
  uuid?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  output_type?: OutputType | null | undefined;
  output_config?: { [k: string]: any } | null | undefined;
  scale_min?: number | null | undefined;
  scale_max?: number | null | undefined;
  version_number?: number | null | undefined;
};

export const TestRunEvaluator$zodSchema: z.ZodType<TestRunEvaluator> = z.object(
  {
    description: z.string().nullable().optional().describe(
      "What the evaluator checks",
    ),
    name: z.string().nullable().optional().describe("Name of the evaluator"),
    output_config: z.record(z.string(), z.any()).nullable().optional().describe(
      "Rubric: the scale values, labels, and colors a verdict maps to",
    ),
    output_type: OutputType$zodSchema.nullable().optional().describe(
      "Verdict shape: pass/fail or a numeric rating",
    ),
    scale_max: z.number().nullable().optional().describe(
      "Highest rating value. Set for rating evaluators",
    ),
    scale_min: z.number().nullable().optional().describe(
      "Lowest rating value. Set for rating evaluators",
    ),
    uuid: z.string().nullable().optional().describe("ID of the evaluator"),
    version_number: z.int().nullable().optional().describe(
      "Evaluator version this run used",
    ),
  },
);
