/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  RoutersTestsEvaluatorRef,
  RoutersTestsEvaluatorRef$zodSchema,
} from "./routerstestsevaluatorref.js";

/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export const TestCreateType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export type TestCreateType = ClosedEnum<typeof TestCreateType>;

export const TestCreateType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]).describe(
  "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation",
);

export type TestCreate = {
  name: string;
  type: TestCreateType;
  config?: { [k: string]: any } | null | undefined;
  evaluators?: Array<RoutersTestsEvaluatorRef> | null | undefined;
};

export const TestCreate$zodSchema: z.ZodType<TestCreate> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "The calibrate test config. Three top-level keys.\n\n- `history` (array, required): the conversation up to the agent's turn. Each item is `{role, content}` with `role` one of `user`, `assistant`, `tool`. A `tool` message also carries `tool_call_id` and `name`.\n- `evaluation` (object, required): `{type, ...}`, where `type` matches the test's `type` (below).\n- `settings` (object, optional): e.g. `{\"language\": \"en\"}`.\n\n`evaluation` by test type:\n- `response`: judge the agent's reply, graded by the linked evaluators. `{\"type\": \"response\"}`\n- `conversation`: append the reply and judge the whole conversation. `{\"type\": \"conversation\"}`\n- `tool_call`: diff the agent's tool calls against expected ones. Add `tool_calls`, a list of `{tool, arguments, accept_any_arguments?}`.\n\nFor `tool_call`, each expected argument value is one of:\n- `{\"match_type\": \"exact\", \"value\": <any>}`: must equal `value`\n- `{\"match_type\": \"llm_judge\", \"criteria\": \"...\"}`: judged against the criteria\n- `{\"match_type\": \"any\"}`: any value, only checks the argument was passed\n\n`response` / `conversation` example:\n```json\n{\n  \"history\": [{\"role\": \"user\", \"content\": \"What is your return policy?\"}],\n  \"evaluation\": {\"type\": \"response\"},\n  \"settings\": {\"language\": \"en\"}\n}\n```\n\n`tool_call` example:\n```json\n{\n  \"history\": [{\"role\": \"user\", \"content\": \"Book room 101 for tomorrow\"}],\n  \"evaluation\": {\n    \"type\": \"tool_call\",\n    \"tool_calls\": [\n      {\n        \"tool\": \"book_room\",\n        \"arguments\": {\n          \"room\": {\"match_type\": \"exact\", \"value\": \"101\"},\n          \"date\": {\"match_type\": \"llm_judge\", \"criteria\": \"tomorrow's date\"}\n        },\n        \"accept_any_arguments\": false\n      }\n    ]\n  }\n}\n```\n\nEvaluators are linked via the separate `evaluators` field, not inside `config`.\n\nOmit to create the test with no config and fill it in later via update.",
  ),
  evaluators: z.array(RoutersTestsEvaluatorRef$zodSchema).nullable().optional()
    .describe(
      "Evaluators to link. Used by `response` and `conversation` tests",
    ),
  name: z.string().describe("Name of the test, unique within the workspace"),
  type: TestCreateType$zodSchema.describe(
    "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation",
  ),
});
