/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { JudgeResult, JudgeResult$zodSchema } from "./judgeresult.js";
import { TestOutput, TestOutput$zodSchema } from "./testoutput.js";

export type TestCaseResult = {
  test_case_id?: string | null | undefined;
  name?: string | null | undefined;
  passed?: boolean | null | undefined;
  reasoning?: string | null | undefined;
  output?: TestOutput | null | undefined;
  test_case?: { [k: string]: any } | null | undefined;
  judge_results?: Array<JudgeResult> | null | undefined;
  latency_ms?: number | null | undefined;
  cost?: number | null | undefined;
};

export const TestCaseResult$zodSchema: z.ZodType<TestCaseResult> = z.object({
  cost: z.number().nullable().optional().describe("Cost of this case in USD"),
  judge_results: z.array(JudgeResult$zodSchema).nullable().optional().describe(
    "One verdict per evaluator, for response and conversation tests. Null for tool-call tests or rows still running",
  ),
  latency_ms: z.number().nullable().optional().describe(
    "Response latency in milliseconds for the agent under test",
  ),
  name: z.string().nullable().optional().describe("Name of the test"),
  output: TestOutput$zodSchema.nullable().optional().describe(
    "The agent's output for this case. Present only when done",
  ),
  passed: z.boolean().nullable().optional().describe(
    "Whether the case passed. Present only when done",
  ),
  reasoning: z.string().nullable().optional().describe(
    "Judge reasoning, or the tool-call diff for tool-call tests",
  ),
  test_case: z.record(z.string(), z.any()).nullable().optional().describe(
    "The input test case definition. Present only when done",
  ),
  test_case_id: z.string().nullable().optional().describe(
    "ID of the test case within the run",
  ),
});
