/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TestCreateResponse = { uuid: string; message: string };

export const TestCreateResponse$zodSchema: z.ZodType<TestCreateResponse> = z
  .object({
    message: z.string().describe("Confirmation message"),
    uuid: z.string().describe("ID of the newly created test"),
  });
