/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ToolCallOutput, ToolCallOutput$zodSchema } from "./toolcalloutput.js";

export type TestOutput = {
  response?: string | null | undefined;
  tool_calls?: Array<ToolCallOutput> | null | undefined;
};

export const TestOutput$zodSchema: z.ZodType<TestOutput> = z.object({
  response: z.string().nullable().optional().describe(
    "The agent's generated reply. Null for tool-call-only cases",
  ),
  tool_calls: z.array(ToolCallOutput$zodSchema).nullable().optional().describe(
    "Tool calls the agent generated. Null when it made none",
  ),
});
