/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { JudgeResult, JudgeResult$zodSchema } from "./judgeresult.js";
import { TestOutput, TestOutput$zodSchema } from "./testoutput.js";

export type TestCaseResult = {
  test_case_id?: string | null | undefined;
  name?: string | null | undefined;
  passed?: boolean | null | undefined;
  reasoning?: string | null | undefined;
  output?: TestOutput | null | undefined;
  test_case?: { [k: string]: any } | null | undefined;
  judge_results?: Array<JudgeResult> | null | undefined;
  latency_ms?: number | null | undefined;
  cost?: number | null | undefined;
};

export const TestCaseResult$zodSchema: z.ZodType<TestCaseResult> = z.object({
  cost: z.number().nullable().optional().describe("Cost of this case (USD)"),
  judge_results: z.array(JudgeResult$zodSchema).nullable().optional().describe(
    "One verdict for each evaluator",
  ),
  latency_ms: z.number().nullable().optional().describe(
    "How long the agent took to respond, in milliseconds",
  ),
  name: z.string().nullable().optional().describe("Name of the test"),
  output: TestOutput$zodSchema.nullable().optional().describe(
    "The agent's output for this case",
  ),
  passed: z.boolean().nullable().optional().describe("Whether the case passed"),
  reasoning: z.string().nullable().optional().describe(
    "The judge's reasoning, or the tool-call diff for a tool-call test",
  ),
  test_case: z.record(z.string(), z.any()).nullable().optional().describe(
    "The test case definition that was run",
  ),
  test_case_id: z.string().nullable().optional().describe(
    "ID of the test case within the run",
  ),
});
