/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { JudgeResult, JudgeResult$zodSchema } from "./judgeresult.js";
import { TestOutput, TestOutput$zodSchema } from "./testoutput.js";

export const TestType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
  General: "general",
} as const;
export type TestType = ClosedEnum<typeof TestType>;

export const TestType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
  "general",
]);

export type TestCaseResult = {
  test_case_id?: string | null | undefined;
  name?: string | null | undefined;
  test_uuid?: string | null | undefined;
  test_type?: TestType | null | undefined;
  passed?: boolean | null | undefined;
  reasoning?: string | null | undefined;
  output?: TestOutput | null | undefined;
  test_case?: { [k: string]: any } | null | undefined;
  inputs?: { [k: string]: any } | null | undefined;
  judge_results?: Array<JudgeResult> | null | undefined;
  latency_ms?: number | null | undefined;
  cost?: number | null | undefined;
  unanswered?: boolean | undefined;
  not_run?: boolean | undefined;
};

export const TestCaseResult$zodSchema: z.ZodType<TestCaseResult> = z.object({
  cost: z.number().nullable().optional().describe("Cost of this case (USD)"),
  inputs: z.record(z.string(), z.any()).nullable().optional().describe(
    "Extra request fields sent to the agent for this case, the agent's `default_inputs` with this case's overrides applied",
  ),
  judge_results: z.array(JudgeResult$zodSchema).nullable().optional().describe(
    "One verdict for each evaluator",
  ),
  latency_ms: z.number().nullable().optional().describe(
    "How long the agent took to respond, in milliseconds",
  ),
  name: z.string().nullable().optional().describe("Name of the test"),
  not_run: z.boolean().default(false).describe(
    "Whether this case never started, because a user stopped the run first. It is counted neither as passed nor as failed",
  ),
  output: TestOutput$zodSchema.nullable().optional().describe(
    "The agent's output for this case",
  ),
  passed: z.boolean().nullable().optional().describe("Whether the case passed"),
  reasoning: z.string().nullable().optional().describe(
    "The judge's reasoning, or the tool-call diff for a tool-call test",
  ),
  test_case: z.record(z.string(), z.any()).nullable().optional().describe(
    "The test case definition that was run",
  ),
  test_case_id: z.string().nullable().optional().describe(
    "ID of the test case within the run",
  ),
  test_type: TestType$zodSchema.nullable().optional().describe(
    "What the test asks of the agent, which decides how a reader draws the case",
  ),
  test_uuid: z.string().nullable().optional().describe(
    "ID of the test this case ran, which is what you pass to read the case on its own",
  ),
  unanswered: z.boolean().default(false).describe(
    "Whether this case produced no answer because the agent or the judge could not be reached, in which case `reasoning` carries the error and `passed` is not a verdict on the agent",
  ),
});
