/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { TestListConfig, TestListConfig$zodSchema } from "./testlistconfig.js";

/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export const TestListResponseType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
/**
 * What the test judges:
 *
 * @remarks
 *
 * - `response`: judges the generated reply
 * - `tool_call`: diffs the generated tool calls
 * - `conversation`: judges the full conversation
 */
export type TestListResponseType = ClosedEnum<typeof TestListResponseType>;

export const TestListResponseType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]).describe(
  "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n",
);

/**
 * Trimmed test shape for list/index endpoints. The full config and hydrated
 *
 * @remarks
 * evaluators live on the detail endpoint (`GET /tests/{uuid}`); the list keeps
 * only what list and attach-dropdown views render.
 */
export type TestListResponse = {
  uuid: string;
  name: string;
  type: TestListResponseType;
  config?: TestListConfig | null | undefined;
  created_at: string;
  updated_at: string;
};

export const TestListResponse$zodSchema: z.ZodType<TestListResponse> = z.object(
  {
    config: TestListConfig$zodSchema.nullable().optional().describe(
      "Trimmed config carrying only the test's description. Fetch the test by ID for the full config and evaluators",
    ),
    created_at: z.string().describe("When the test was created (ISO 8601 UTC)"),
    name: z.string().describe("Name of the test"),
    type: TestListResponseType$zodSchema.describe(
      "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n",
    ),
    updated_at: z.string().describe(
      "When the test was last updated (ISO 8601 UTC)",
    ),
    uuid: z.string().describe("Unique ID for the test"),
  },
).describe(
  "Trimmed test shape for list/index endpoints. The full config and hydrated\nevaluators live on the detail endpoint (`GET /tests/{uuid}`); the list keeps\nonly what list and attach-dropdown views render.",
);
