/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  RoutersTestsEvaluatorRef,
  RoutersTestsEvaluatorRef$zodSchema,
} from "./routerstestsevaluatorref.js";

export const TestUpdateType = {
  Response: "response",
  ToolCall: "tool_call",
  Conversation: "conversation",
} as const;
export type TestUpdateType = ClosedEnum<typeof TestUpdateType>;

export const TestUpdateType$zodSchema = z.enum([
  "response",
  "tool_call",
  "conversation",
]);

export type TestUpdate = {
  name?: string | null | undefined;
  type?: TestUpdateType | null | undefined;
  config?: { [k: string]: any } | null | undefined;
  evaluators?: Array<RoutersTestsEvaluatorRef> | null | undefined;
};

export const TestUpdate$zodSchema: z.ZodType<TestUpdate> = z.object({
  config: z.record(z.string(), z.any()).nullable().optional().describe(
    "The calibrate test config. Three top-level keys.\n\n- `history`: the required conversation up to the agent's turn. Each item is `{role, content}` with `role` one of `user`, `assistant`, `tool`. A `tool` message also carries `tool_call_id` and `name`.\n- `evaluation`: the required `{type, ...}`, where `type` matches the test's `type` below.\n- `settings`: an optional object, e.g. `{\"language\": \"en\"}`.\n\n`evaluation` by test type:\n- `response`: judge the agent's reply, graded by the linked evaluators. `{\"type\": \"response\"}`\n- `conversation`: append the reply and judge the whole conversation. `{\"type\": \"conversation\"}`\n- `tool_call`: diff the agent's tool calls against expected ones. Add `tool_calls`, a list of `{tool, arguments, accept_any_arguments?}`.\n\nFor `tool_call`, each expected argument value is one of:\n- `{\"match_type\": \"exact\", \"value\": <any>}`: must equal `value`\n- `{\"match_type\": \"llm_judge\", \"criteria\": \"...\"}`: judged against the criteria\n- `{\"match_type\": \"any\"}`: any value, only checks the argument was passed\n\n`response` / `conversation` example:\n```json\n{\n  \"history\": [{\"role\": \"user\", \"content\": \"What is your return policy?\"}],\n  \"evaluation\": {\"type\": \"response\"},\n  \"settings\": {\"language\": \"en\"}\n}\n```\n\n`tool_call` example:\n```json\n{\n  \"history\": [{\"role\": \"user\", \"content\": \"Book room 101 for tomorrow\"}],\n  \"evaluation\": {\n    \"type\": \"tool_call\",\n    \"tool_calls\": [\n      {\n        \"tool\": \"book_room\",\n        \"arguments\": {\n          \"room\": {\"match_type\": \"exact\", \"value\": \"101\"},\n          \"date\": {\"match_type\": \"llm_judge\", \"criteria\": \"tomorrow's date\"}\n        },\n        \"accept_any_arguments\": false\n      }\n    ]\n  }\n}\n```\n\nEvaluators are linked via the separate `evaluators` field, not inside `config`.\n\nReplaces the stored config. Omit to leave unchanged",
  ),
  evaluators: z.array(RoutersTestsEvaluatorRef$zodSchema).nullable().optional()
    .describe(
      "New evaluator links for the test. Omit to leave unchanged. An empty list clears them, except on `conversation` tests, which must keep at least one",
    ),
  name: z.string().nullable().optional().describe(
    "New test name. Omit to leave unchanged",
  ),
  type: TestUpdateType$zodSchema.nullable().optional().describe(
    "What the test judges:\n\n- `response`: judges the generated reply\n- `tool_call`: diffs the generated tool calls\n- `conversation`: judges the full conversation\n\n\nImmutable. Omit it, or send the current value",
  ),
});
