/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TestListConfig = { description?: string | null | undefined };

export const TestListConfig$zodSchema: z.ZodType<TestListConfig> = z.object({
  description: z.string().nullable().optional().describe(
    "Short description of the test, shown in list views and searched on",
  ),
});
