/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ToolCallOutput = {
  tool: string;
  arguments?: { [k: string]: any } | null | undefined;
  output?: any | null | undefined;
};

export const ToolCallOutput$zodSchema: z.ZodType<ToolCallOutput> = z.object({
  arguments: z.record(z.string(), z.any()).nullable().optional().describe(
    "Arguments the agent passed to the tool. Null if none",
  ),
  output: z.any().nullable().optional().describe(
    "Tool execution result (any JSON value). Present only when the agent runs the tool and returns its result",
  ),
  tool: z.string().describe("Name of the tool the agent called"),
});
