/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TraceToolCall, TraceToolCall$zodSchema } from "./tracetoolcall.js";

export type TraceOutput = {
  response?: string | null | undefined;
  tool_calls?: Array<TraceToolCall> | null | undefined;
};

export const TraceOutput$zodSchema: z.ZodType<TraceOutput> = z.object({
  response: z.string().nullable().optional().describe(
    "The assistant reply text for this turn. Omit for turns that only issued tool calls",
  ),
  tool_calls: z.array(TraceToolCall$zodSchema).nullable().optional().describe(
    "Tool calls the agent issued for this turn. Omit for plain text replies",
  ),
});
