/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TraceMetadataEntry = { key: string; value: string };

export const TraceMetadataEntry$zodSchema: z.ZodType<TraceMetadataEntry> = z
  .object({
    key: z.string().describe("Name of the metadata entry"),
    value: z.string().describe("Value of the metadata entry"),
  });
