/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TraceMetadataEntry,
  TraceMetadataEntry$zodSchema,
} from "./tracemetadataentry.js";
import { TraceOutput, TraceOutput$zodSchema } from "./traceoutput.js";
import { TraceTurn, TraceTurn$zodSchema } from "./traceturn.js";

export type TraceIngest = {
  agent_id: string;
  message_id?: string | null | undefined;
  conversation_id?: string | null | undefined;
  input: Array<TraceTurn>;
  output: TraceOutput;
  metadata?: Array<TraceMetadataEntry> | null | undefined;
};

export const TraceIngest$zodSchema: z.ZodType<TraceIngest> = z.object({
  agent_id: z.string().describe(
    "ID of the agent that produced the turn. Must be an agent in your workspace",
  ),
  conversation_id: z.string().nullable().optional().describe(
    "Your own ID for the conversation this turn belongs to, stored for reference only. Omit if you have none",
  ),
  input: z.array(TraceTurn$zodSchema).describe(
    "Conversation history up to the reported output, oldest turn first, in OpenAI chat format",
  ),
  message_id: z.string().nullable().optional().describe(
    "Your own ID for the last user message in `input`, stored for reference only. Omit if you have none",
  ),
  metadata: z.array(TraceMetadataEntry$zodSchema).nullable().optional()
    .describe(
      "Key-value pairs stored with the trace. Prefer OTel `gen_ai.*` key names where they fit. Omit if you have none",
    ),
  output: TraceOutput$zodSchema,
});
