/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";

export type TraceTurn = {
  role: string;
  content?: string | null | undefined;
  AdditionalProperties?: { [k: string]: any };
};

export const TraceTurn$zodSchema: z.ZodType<TraceTurn> = collectExtraKeys$(
  z.object({
    content: z.string().nullable().optional().describe(
      "Message text. Omit for turns that only carry tool calls",
    ),
    role: z.string().describe(
      "Message author role in the conversation history",
    ),
  }).catchall(z.any()),
  "AdditionalProperties",
  true,
);

export const TraceTurn$zodSchemaOutbound: z.ZodType<any> = z.object({
  AdditionalProperties: z.record(z.string(), z.any()).optional(),
  content: z.nullable(z.string()).optional(),
  role: z.string(),
}).transform((v) => {
  const { AdditionalProperties, ...rest } = v;
  return {
    ...rest,
    ...AdditionalProperties,
  };
});
