/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TraceIngestResponse = {
  uuid: string;
  message_id?: string | null | undefined;
  conversation_id?: string | null | undefined;
  created_at: string;
};

export const TraceIngestResponse$zodSchema: z.ZodType<TraceIngestResponse> = z
  .object({
    conversation_id: z.string().nullable().optional().describe(
      "The conversation ID you sent, if any",
    ),
    created_at: z.string().describe(
      "When the trace was created (ISO 8601 UTC)",
    ),
    message_id: z.string().nullable().optional().describe(
      "The message ID you sent, if any",
    ),
    uuid: z.string().describe("Unique ID for the trace"),
  });
