/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TraceToolCall = {
  tool: string;
  arguments?: { [k: string]: any } | null | undefined;
};

export const TraceToolCall$zodSchema: z.ZodType<TraceToolCall> = z.object({
  arguments: z.record(z.string(), z.any()).nullable().optional().describe(
    "Argument values the agent passed to the tool. Omit when the call had none",
  ),
  tool: z.string().describe("Name of the tool the agent called"),
});
