/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AgentUpdate, AgentUpdate$zodSchema } from "./agentupdate.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  RoutersAgentsAgentResponse,
  RoutersAgentsAgentResponse$zodSchema,
} from "./routersagentsagentresponse.js";

export type UpdateAgentEndpointAgentsAgentUuidPutRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
  xOrgUUID?: string | null | undefined;
  body: AgentUpdate;
};

export const UpdateAgentEndpointAgentsAgentUuidPutRequest$zodSchema: z.ZodType<
  UpdateAgentEndpointAgentsAgentUuidPutRequest
> = z.object({
  agent_uuid: z.string().describe("The agent to update."),
  body: AgentUpdate$zodSchema,
  xAPIKey: z.string().nullable().optional(),
  xOrgUUID: z.string().nullable().optional(),
});

export type UpdateAgentEndpointAgentsAgentUuidPutResponse =
  | RoutersAgentsAgentResponse
  | HTTPValidationError;

export const UpdateAgentEndpointAgentsAgentUuidPutResponse$zodSchema: z.ZodType<
  UpdateAgentEndpointAgentsAgentUuidPutResponse
> = z.union([
  RoutersAgentsAgentResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
