/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnnotatorResponse,
  AnnotatorResponse$zodSchema,
} from "./annotatorresponse.js";
import {
  AnnotatorUpdate,
  AnnotatorUpdate$zodSchema,
} from "./annotatorupdate.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";

export type UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutRequest = {
  annotator_uuid: string;
  xAPIKey?: string | null | undefined;
  body: AnnotatorUpdate;
};

export const UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutRequest$zodSchema:
  z.ZodType<UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutRequest> = z
    .object({
      annotator_uuid: z.string().describe("Annotator to update"),
      body: AnnotatorUpdate$zodSchema,
      xAPIKey: z.string().nullable().optional(),
    });

export type UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutResponse =
  | AnnotatorResponse
  | HTTPValidationError;

export const UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutResponse$zodSchema:
  z.ZodType<UpdateAnnotatorEndpointAnnotatorsAnnotatorUuidPutResponse> = z
    .union([
      AnnotatorResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
