/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import { TestResponse, TestResponse$zodSchema } from "./testresponse.js";
import { TestUpdate, TestUpdate$zodSchema } from "./testupdate.js";

export type UpdateTestEndpointTestsTestUuidPutRequest = {
  test_uuid: string;
  xAPIKey?: string | null | undefined;
  body: TestUpdate;
};

export const UpdateTestEndpointTestsTestUuidPutRequest$zodSchema: z.ZodType<
  UpdateTestEndpointTestsTestUuidPutRequest
> = z.object({
  body: TestUpdate$zodSchema,
  test_uuid: z.string().describe("Test to update"),
  xAPIKey: z.string().nullable().optional(),
});

export type UpdateTestEndpointTestsTestUuidPutResponse =
  | TestResponse
  | HTTPValidationError;

export const UpdateTestEndpointTestsTestUuidPutResponse$zodSchema: z.ZodType<
  UpdateTestEndpointTestsTestUuidPutResponse
> = z.union([
  TestResponse$zodSchema,
  HTTPValidationError$zodSchema,
]);
