/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Loc = string | number;

export const Loc$zodSchema: z.ZodType<Loc> = z.union([
  z.string(),
  z.int(),
]);

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export const ValidationError$zodSchema: z.ZodType<ValidationError> = z.object({
  loc: z.array(z.union([
    z.string(),
    z.int(),
  ])),
  msg: z.string(),
  type: z.string(),
});
