/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VariableSpec = {
  name: string;
  description?: string | null | undefined;
  default?: string | null | undefined;
};

export const VariableSpec$zodSchema: z.ZodType<VariableSpec> = z.object({
  default: z.string().nullable().optional().describe(
    "Default value used when you omit this variable. Omit for no default",
  ),
  description: z.string().nullable().optional().describe(
    "What the variable is for. Omit if self-evident",
  ),
  name: z.string().describe(
    "Name of a `{{\"{{\"}}placeholder}}` used in the system prompt",
  ),
});
