/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentVerifyRequest,
  AgentVerifyRequest$zodSchema,
} from "./agentverifyrequest.js";
import {
  HTTPValidationError,
  HTTPValidationError$zodSchema,
} from "./httpvalidationerror.js";
import {
  VerifyConnectionResponse,
  VerifyConnectionResponse$zodSchema,
} from "./verifyconnectionresponse.js";

export type VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostRequest = {
  agent_uuid: string;
  xAPIKey?: string | null | undefined;
  body: AgentVerifyRequest;
};

export const VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostRequest$zodSchema:
  z.ZodType<VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostRequest> = z
    .object({
      agent_uuid: z.string().describe("The agent whose connection to verify"),
      body: AgentVerifyRequest$zodSchema,
      xAPIKey: z.string().nullable().optional(),
    });

export type VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostResponse =
  | VerifyConnectionResponse
  | HTTPValidationError;

export const VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostResponse$zodSchema:
  z.ZodType<VerifyAgentConnectionAgentsAgentUuidVerifyConnectionPostResponse> =
    z.union([
      VerifyConnectionResponse$zodSchema,
      HTTPValidationError$zodSchema,
    ]);
