/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VerifyConnectionResponse = {
  success: boolean;
  error?: string | null | undefined;
  sample_response?: { [k: string]: any } | null | undefined;
};

export const VerifyConnectionResponse$zodSchema: z.ZodType<
  VerifyConnectionResponse
> = z.object({
  error: z.string().nullable().optional().describe(
    "Reason the verification failed",
  ),
  sample_response: z.record(z.string(), z.any()).nullable().optional().describe(
    "Sample output returned by the agent during verification",
  ),
  success: z.boolean().describe(
    "True if the agent responded successfully to the verification probe",
  ),
});
