/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VersionCreateResponse = {
  version_uuid: string;
  version_number: number;
};

export const VersionCreateResponse$zodSchema: z.ZodType<VersionCreateResponse> =
  z.object({
    version_number: z.int().describe(
      "The version's number. The first version is 1, and it goes up by one for each new version of the evaluator",
    ),
    version_uuid: z.string().describe("ID of the newly created version"),
  });
